### ISSUE TITLE
Memory leaks in manager.connect()

### ISSUE THREAD

**Issue by bimusiek** [pusher/pusher-websocket-swift#101]
Hey guys,
we are investigating memory leaks with PusherManager and we found that method `connect` leaks quite a lot for us (~700kb) while calling it 3 times.

We have in our one instance init class

``` swift
 let options = PusherClientOptions(
            authMethod: AuthMethod.authRequestBuilder(authRequestBuilder: AuthRequestBuilder(delegate: self))
        )
        manager = Pusher(
            key: config.PUSHER_KEY,
            options: options
        )
```

so `Pusher` is always one instance.

Then, when someone change user in our app we call

``` swift

        self.privateChannel?.unbindAll()
        self.privateChannel = nil

        self.manager.unbindAll()
        self.manager.disconnect()

        self.manager.connect()

        let channelName = "private-user-\(userId)"
        DLOG("Subscribing to private channel named: \(channelName)")
        privateChannel = self.manager.subscribe(channelName)
        _ = privateChannel?.bind(eventName: "update", callback: { [weak self] (response) in
            DLOG("Pusher update: \(response)")
            if let data = response as? [String:AnyObject] {
                let type = data["type"] as? String
                let eventType = PusherEventEntity.fromString(type)

                self?.invokeDelegate({ (delegate) -> () in
                    delegate.updateEvent(eventType, data: data as AnyObject)
                })
            }
        })
```

<img width="1032" alt="screenshot 2016-10-20 18 11 54" src="https://cloud.githubusercontent.com/assets/1025588/19568154/bca46efc-96f0-11e6-9213-85aef3b2d1bd.png">

Any ideas?

**Comment by bimusiek** [comment]
If someone had the same issue, here is solution.

You don't have to disconnect and connect when you switch user. Pusher does authentication when subscribing, so we connect once now and then we unsubscribe and subscribe again. :) No more leaks.

**Comment by hamchapman** [comment]
Interesting! 

Thanks for writing this up. I'll hopefully get some time soon to take a look into this.

**Comment by anlaital** [comment]
This was also causing us considerable pain so I fixed this quickly. This could use some refactoring, but I suppose that's something up for discussion. :)

There is now a pull request for this https://github.com/pusher/pusher-websocket-swift/pull/105

**Comment by anlaital** [comment]
I also noticed that `authRequestBuilder` in `PusherClientOptions` retains the object given to it. This will cause a memory leak in what I assume to be a very common scenario of there being a single class that both retains the `Pusher` instance and also implements the `AuthRequestBuilderProtocol` protocol.

**Comment by hamchapman** [comment]
Thanks for the PR and the note about the `AuthRequestBuilderProtocol`. I've deprecated the old function and added a new one that uses the `URLRequest` type (instead of `NSMutableURLRequest`) and also instead takes just the channel name rather than the whole `PusherChannel` object.

Also merged in your PR with the memory leak fixes and so will make a new release later today (4.0.2). 👍
