### ISSUE TITLE
Question: How to monitor connection states?

### ISSUE THREAD

**Issue by daande** [pusher/pusher-websocket-swift#11]
I was wondering if it is currently possible to monitor connection states?

**Comment by hamchapman** [comment]
Not currently - it's something that I want added in the future. Just need to find some time! 

Pull requests are more than welcome :+1:

**Comment by daande** [comment]
I will take a look later today.  Can you label this as an enhancement / assign to me?

**Comment by tomhut** [comment]
@daande @hamchapman Going to take a look at this next week, how do people feel about delegate callbacks and/or a closure for connection state changes with perhaps a bool property for in-line state checking?

- Tom

**Comment by daande** [comment]
I was planning on using delegate callbacks (got busy at work since I posted this). And a bool property seems fine or even an enum for connection state so we can show more than is connected or is not connected. Maybe have one for idle (has yet to connect), connected, disconnected.

**Comment by tomhut** [comment]
@daande I know that feeling! I will be hacking away over here (unless you already have a fork) https://github.com/tomhut/pusher-websocket-swift/tree/enhancement-connectionState

**Comment by hamchapman** [comment]
I'm happy with either a closure for connection state changes or for delegate callbacks. Either would be an awesome addition! Thanks guys :+1:

**Comment by hamchapman** [comment]
I've added a `ConnectionStateDelegate` that you can implement pretty easily to get the state changes (`Connected`, `Connecting`, `Disconnecting`, `Disconnected`)
