### ISSUE TITLE
Sending "events" or messages

### ISSUE THREAD

**Issue by danielrhodes** [pusher/pusher-websocket-swift#114]
Correct me if I am wrong, but I could not find any place in the documentation where you can send messages. Is this a receive-only library?

**Comment by hamchapman** [comment]
You can send client events (https://pusher.com/docs/client_api_guide/client_events#trigger-events) using the library. 

This is done by calling `.trigger` on a private or presence channel - this is the relevant code: https://github.com/pusher/pusher-websocket-swift/blob/master/Source/PusherChannel.swift#L121-L128

This should be documented in the readme though, so I'll make sure that it gets added 👍

**Comment by danielrbrowne** [comment]
This is still relevant.
