### ISSUE TITLE
unbindAll(forEventName eventName: String)

### ISSUE THREAD

**Issue by cankocoglu** [pusher/pusher-websocket-swift#118]
App crashes while trying to disconnect. I want to change my view controller with the incoming pusher message, everything is fine until the perform segue triggered. It always stucked at unbind functions.

```swift
open func unbindAll(forEventName eventName: String) {
    self.eventHandlers[eventName] = []
}
```

For this function, eventName value is always lldb. so app crashes all the time. If I don't use eventName in bind function, no errors shown.

From your code 
```swift
myChannel.bind(eventName: "new-price", callback: { (data: Any?) -> Void in
    if let data = data as? [String : AnyObject] {
        if let price = data["price"] as? String, company = data["company"] as? String {
            print("\(company) is now priced at \(price)")
        }
    }
}) 
--> NOT WORKS

pusher.bind(callback: { (data: Any?) -> Void in
    if let data = data as? [String : AnyObject] {
        if let commenter = data["commenter"] as? String, message = data["message"] as? String {
            print("\(commenter) wrote \(message)")
        }
    }
}) 
--> WORKS, but in that case app will crash at:

open func unbindAll(forEventName eventName: String) {
    self.eventHandlers[eventName] = []
}
```

function. there is a problem with eventName i guess but I couldn't solve that.

**Comment by hamchapman** [comment]
I need some more information to be able to understand the problem that you're encountering.

Could you perhaps attach a project with sufficient code in it to demonstrate the problem and how to recreate it?

THanks!

**Comment by hamchapman** [comment]
@cankocoglu just checking in to see if you're still encountering the problem? If you are, a sample project would be a massive help in terms of debugging the issues you're facing!

**Comment by hamchapman** [comment]
Closing as stale.
