### ISSUE TITLE
Does master support swift3 and push-notifications?

### ISSUE THREAD

**Issue by r-a-o** [pusher/pusher-websocket-swift#120]
Couldn't figure out if the master branch supports Swift3 ? and whether it includes support for Push Notifications feature? If not, which branch has Swift3+pushNotification ?
Can someone please clarify on this? Its not mentioned in the readme, no mention in any of the release notes as well!

Thanks!

**Comment by hamchapman** [comment]
Yep it supports Swift 3 and has support for push notifications.

**Comment by r-a-o** [comment]
Great! I will add it to the readme when I find time.
