### ISSUE TITLE
XCode 8.3(beta) Compiler Warnings

### ISSUE THREAD

**Issue by grizzly** [pusher/pusher-websocket-swift#125]
Seems, there are some changed Swift rules. 

Pusher.swift:133:102: String interpolation produces a debug description for an optional value; did you mean to make this explicit?

And a lot of more similar issues. Is there any schedule for a compatible library?

**Comment by hamchapman** [comment]
I'll try to take a look at this this afternoon

**Comment by hamchapman** [comment]
I've pushed a branch https://github.com/pusher/pusher-websocket-swift/tree/swift-3.1

**Comment by grizzly** [comment]
Thx

**Comment by grizzly** [comment]
Sorry, closed to early. One last warning remains:

PusherConnection.swift:540:42: 'requestFor(socketID:channel:)' is deprecated: use requestFor(socketID: String, channelName: String) -> URLRequest? instead

**Comment by hamchapman** [comment]
That was is an intentional deprecation warning, and tied to anything to do with the latest beta. It's coming from here: https://github.com/pusher/pusher-websocket-swift/blob/swift-3.1/Source/PusherClientOptions.swift#L22-L23
