### ISSUE TITLE
Custom timeout

### ISSUE THREAD

**Issue by daCelky** [pusher/pusher-websocket-swift#130]
Hi,

I'm currently stuck in a big issue about connection instability and interruptions.

We're doing a cross-platform application that use Pusher to get C2C connection.

On Android we're able to set an activityTimeout / pongTimeOut.

I don't manage to find this setting in the swift version of the library, and It would be a real pain to re-do a timeout system by hand when it's easy usable in Android.

If you can advise me on how should I handle a loss of connection to get the client out of presence/private channel by closing associated sockets in a certain time after loss. (by default it seems to be around 3 minutes before Pusher told from presence channel that a client is removed from channel.

Thanks in advance!

**Comment by hamchapman** [comment]
Ah this isn't something that's been requested before but it shouldn't be too difficult to add, I imagine.

I'll have to look at the underlying web socket library to see if they expose some hooks for ping-pong mechanisms.

Or perhaps you want to take a look, if you're interested in creating a pull request? No pressure though! 😁

**Comment by daCelky** [comment]
Hi again !

At first thanks for this really quick response ! 

Unfortunately, I'm not sure i'll be able to create something consistent with the native socket library nor anything close to it, I'm not that experienced in Swift or in iOS environnement actually.

But if you manage to find something, I'd be glad to try it out and make it fit with a cross-platform Pusher integration !

**Comment by hamchapman** [comment]
This functionality has been added in the `cleanup-crash-fix` branch, PR here: https://github.com/pusher/pusher-websocket-swift/pull/178

If anyone here tries it out, please let me know how it goes 👍
