### ISSUE TITLE
Potentially breaking changes in 4.0.2

### ISSUE THREAD

**Issue by SudeepSidhu** [pusher/pusher-websocket-swift#135]
While 4.0.2 indicates that it's simply a new patch version after 4.0.1, there was a crucial change regarding what queue the callbacks happen on.  Pre 4.0.2 the callbacks went on the main thread but in 45bebf7b4eb81f795285b9de77861c2b3a0d6b0f this was changed. Now the callbacks aren't happening on the main thread. 

So if you were working with the assumption that the callbacks would take place on the main thread, you're likely going to see some odd behaviour, especially if running UI code. In some cases this may even lead to a crash.

Additionally there is no documentation related to assumptions about callbacks. Regardless of the resolution, we should add some documentation.

I'm not sure what's the best way to resolve this (going back to using the main queue would be the simplest solution) so I'll defer to your judgement on that. But I'll happily throw up a PR if we agree on something.

Thanks!

**Comment by hamchapman** [comment]
Good spot - I had forgotten about that change when I made the new release. Sorry about that.

How about for now I remove this line https://github.com/pusher/pusher-websocket-swift/blob/45bebf7b4eb81f795285b9de77861c2b3a0d6b0f/Source/PusherSwift.swift#L43 and make a 4.0.3 release (and pull the 4.0.2 release)?

What do you think?

(Thanks again for the spot!)

**Comment by SudeepSidhu** [comment]
I agree, for now it's the best option.

**Comment by hamchapman** [comment]
I pulled the 4.0.2 release and made a 4.1.0 release (added in a couple of other changes that had been pending for a while). Thanks again!
