### ISSUE TITLE
error: module file's minimum deployment target is ios9.0

### ISSUE THREAD

**Issue by RyanLii** [pusher/pusher-websocket-swift#138]
### What is the issue?

I am trying to use swift pusher 4.1.0 by carthage, got the error "error: module file's minimum deployment target is ios9"

couldn't compile the project until I changed my target from iOS 8.0 to 9.0
So pusher's target is iOS 9? Cause I checked the podspec it said iOS 8.0. 
a little bit confused by that 
### Is it a crash report? Submit stack traces or anything that you think would help
nope
...

### Any improvements you suggest

...

---- 

CC @pusher/mobile

**Comment by hamchapman** [comment]
This will be fixed in the next release, which I'll push out today. Apologies for the slow response.
