### ISSUE TITLE
PusherSwift doesn't not compile in XCode 9 against Swift 3.2

### ISSUE THREAD

**Issue by BrendanBuono** [pusher/pusher-websocket-swift#139]
### What is the issue?
PusherSwift doesn't not compile in XCode 9 against Swift 3.2
... 

### Is it a crash report? Submit stack traces or anything that you think would help
No crash, but the CryptoSwiftHMACModule.swift file seems to be the source of most of the errors
...

### Any improvements you suggest

...

---- 

CC @pusher/mobile

**Comment by dk-bbuono** [comment]
The problem seems to be that >= Swift 3.2 is looking for `@_specialize(where T == UInt8)` whereas Swift 3.1 wants `@_specialize(UInt8)`

**Comment by BrendanBuono** [comment]
The problem seems to be that >= Swift 3.2 is looking for `@_specialize(where T == UInt8)` whereas Swift 3.1 wants `@_specialize(UInt8)`

**Comment by BrendanBuono** [comment]
I submitted  pull request #141 to fix this

**Comment by hamchapman** [comment]
Fixed in #145
