### ISSUE TITLE
Crash in `modifySubscription` function

### ISSUE THREAD

**Issue by mansishah278** [pusher/pusher-websocket-swift#143]
<img width="816" alt="screen shot 2017-06-09 at 9 49 04 am" src="https://user-images.githubusercontent.com/22022743/26974621-cd4a4740-4d39-11e7-94f3-0248ddce8d4a.png">
Multiple Crash occurrences in: **NativePusher.swift** file

Any **improvements** you suggest: _Guard the scenario when clientID is nil by guard let or if let. Also, guard let or if let if the URL is valid URL instead of forcefully unwrapping_

CC @pusher/mobile

**Comment by mansishah278** [comment]
This line is generating multiple crashes. Is it because the clientID is forcefully unwrapped?

**Comment by hamchapman** [comment]
I feel like it must be some concurrency thing that hasn't been considered because this line: https://github.com/pusher/pusher-websocket-swift/blob/master/Source/NativePusher.swift#L199 suggests that there is already a `nil` check for the `clientId`

**Comment by mansishah278** [comment]
which concurrency thing, can you please elaborate?

**Comment by mansishah278** [comment]
Also it could be the line
 URLRequest(url: URL(string: url)!)
A valid Url might not be getting generated

**Comment by mansishah278** [comment]
<img width="1134" alt="screen shot 2017-06-11 at 7 06 16 pm" src="https://user-images.githubusercontent.com/22022743/27019771-f3e37afe-4f58-11e7-8450-30343c4128b7.png">
