### ISSUE TITLE
pure objective-c library

### ISSUE THREAD

**Issue by lechium** [pusher/pusher-websocket-swift#146]
### What is the issue?

... Swift libraries are a non starter, need old documentation information that relates to the unfortunately obsoleted library. Need to set up a global channel and am having problems finding the requisite information.

### Is it a crash report? Submit stack traces or anything that you think would help

...

### Any improvements you suggest

don't force people to use swift.
...

---- 

CC @pusher/mobile

**Comment by hamchapman** [comment]
Why are Swift libraries a non-starter for you? What old documentation are you referring to, and which obsoleted library? Also what global channel are you talking about?

You can always use [libPusher](https://github.com/pusher/libPusher) if you'd prefer an Objective-C library.

**Comment by lechium** [comment]
I think i probably meant public channel. i figured out my problem. however to elaborate why swift libraries are a non starter.

1) fragile, apple has taken way to long to care about API/ABI stability
2) dreadful build speeds
3) tether you to the latest version of Xcode
4) drastic increase in app binary size
5) with all its flaws swift has zero benefit over obj-c, & strict typing is counterproductive. so i refuse to use any swift in any of my projects.

don't know why i had trouble finding the libpusher repo again since its the one im already using.

thanks.
