### ISSUE TITLE
When does this library support the watchOS?

### ISSUE THREAD

**Issue by gaozhan1991** [pusher/pusher-websocket-swift#150]
I tried to use the PusherSwift on watchOS platform.
But when running the command "pod install", I got an error:
.....
[!] The platform of the target `Carepoint WatchKit App` (watchOS 3.2) is not compatible with `PusherSwift (4.2.0)`, which does not support `watchos`.
.....

**Comment by hamchapman** [comment]
Currently PusherSwift doesn't work with watchOS. It's something that I'm looking into though, as it involves Starscream (the websocket dependency that PusherSwift uses) having support for watchOS.

I'll leave this issue open and update when I have more news.

**Comment by gaozhan1991** [comment]
Thanks for your reply.

**Comment by hamchapman** [comment]
There's no specific date I can give you at the current time. I'll update this issue when I have more information. Thanks!

**Comment by hamchapman** [comment]
watchOS support has been added to Starscream so I'll try to find time to look into adding support for it soon!

**Comment by gaozhan1991** [comment]
Thanks for your effort.

**Comment by gaozhan1991** [comment]
Hi.
I need your help.
This is the code snippet using javascript. 

client = new Pusher('123', 
				{
					encrypted: true,
					authEndpoint: 'xxx.yyy.zzz',
					auth: {
							params: {
							  'setting1': value1,
							  'setting2': value2,
							  'setting3': value3
							},
							headers: {
							  'id': id
							}
					  }
				}
			);

I want the code corresponding to this one using Swift.
Anything would be much appreciated.

**Comment by hamchapman** [comment]
You'd want something like this:

```swift
class AuthRequestBuilder: AuthRequestBuilderProtocol {
    func requestFor(socketID: String, channelName: String) -> URLRequest? {
        let authEndpointComponents = URLComponents(string: "xxx.yyy.zzz")
        authEndpointComponents?.queryItems = [
            "setting1": value1,
            "setting2": value2,
            "setting3": value3
        ]
        let request = NSMutableURLRequest(url: authEndpointComponents!.url!)
        request.httpMethod = "POST"
        request.httpBody = "socket_id=\(socketID)&channel_name=\(channel.name)".data(using: String.Encoding.utf8)
        request.addValue(id, forHTTPHeaderField: "id")
        return request
    }
}


let options = PusherClientOptions(
    authMethod: AuthMethod.authRequestBuilder(authRequestBuilder: AuthRequestBuilder())
)
client = Pusher(key: "123", options: options)
```

**Comment by gaozhan1991** [comment]
Thanks so much.
So when would the version for watchOS be expected to release ?

**Comment by hamchapman** [comment]
I can't give an estimate on the date I'm afraid. It's something that we're keen to add though.

**Comment by gaozhan1991** [comment]
What can I help you ?

**Comment by gaozhan1991** [comment]
Hi, 
You have any updates ?

Sorry, but I couldn't understand the code snippet, you explained before, enough.
So I'd like you to analyze the following raw code, written in javascript, again.
 
personalWatchfaceApp.service('PusherService', ['$rootScope',  '$http', '$pusher', function ($rootScope, $http, $pusher) {
	var service = {};
	
	var pusher = null;
	var channel = null;
	
	var pusher_subscription_succeeded = function(members) {
        }
	
	var pusher_member_removed = function(member) {
	}
	
	var pusher_member_added = function(member) {
	}
	
	var client_joinconf = function(data) {
	}
	
	var client_triggerPB = function(data) {
	}
	
	var client_cancelPB = function(data) {
	}
	
	var client_request = function(data) {
	}
 	
    service.init = function() {
    	var gear_id = "abcdef";
    	
    	//unbind everything
    	if(pusher!=null)
    	{
    		pusher.unsubscribe('presence-'+gear_id);
    		pusher.disconnect();
    		pusher=null;
    	}
    	
    	if(channel!=null)
    	{
    		channel.unbind('pusher:subscription_succeeded', pusher_subscription_succeeded);
    		channel.unbind('pusher:member_removed', pusher_member_removed);
    		
    		channel.unbind('client-joinconf', client_joinconf);
    		channel.unbind('client-triggerPB', client_triggerPB);
    		channel.unbind('client-cancelPB', client_cancelPB);
    		channel=null;
        }
        
        let value1 = "abc1"
        let value2 = "abc2"
        let value3 = "abc3"

    	client = new Pusher('1234567890', 
				{
					encrypted: true,
					authEndpoint: 'https://login.xxx.com/pusher/auth',
					auth: {
							params: { // {key: value} pairs
							  'setting1': value1,
							  'setting1': value2,
							  'setting3': value3,
							},
							headers: { // {key: value} pairs
							  'gearid': gear_id
							}
					  }
				}
			);
    	
    	pusher = $pusher(client);
    	 	
		channel = pusher.subscribe('presence-'+gear_id);
		
		channel.bind('pusher:subscription_succeeded', pusher_subscription_succeeded);

		channel.bind('pusher:member_removed', pusher_member_removed);
		channel.bind('pusher:member_added', pusher_member_added);
		
		channel.bind('client-joinconf', client_joinconf);
		channel.bind('client-triggerPB', client_triggerPB);
		channel.bind('client-cancelPB', client_cancelPB);
		channel.bind('client-request', client_request);
 	} 
 	
 	return service;
}]);

If the version for iWatch isn't released, I am going to implement the part for iOS first.
Thanks for your support.

**Comment by gaozhan1991** [comment]
Hi,

**Comment by gaozhan1991** [comment]
Hi

**Comment by gaozhan1991** [comment]
The iOS app in the background that uses the pusher service can receive the event from the service real-time.
Is this possible?

**Comment by gaozhan1991** [comment]
Help me.

**Comment by hamchapman** [comment]
If the app is backgrounded then the web socket connection will be cleaned up after a maximum of 3 minutes and so you'll very quickly not be able to receive events from Pusher.

You'll want to use native push notifications if you need to push data to a user's app when it could be in the background.

**Comment by gaozhan1991** [comment]
Thanks for your reply.
It is positively necessary for me to solve this problem even on iOS.
So I want to discuss more quickly with you via other means of communication.
I will certainly pay for your support.

**Comment by hamchapman** [comment]
It's really a question of what your use case is. 

If you need to get data to the device no matter the state of the app on the end user's device then push notifications are your best (arguably only) option. 

If you need to get updates to a user while they're active in the app then using Pusher's websocket service is a great option.

Making Pusher's websocket service work in the background is not really a viable option (unless your app happens to be some sort of a VoIP app).

**Comment by gaozhan1991** [comment]
My use case is the following:
The event is triggered in the backend server website by clicking on one button.(I use the browser app, Safari, on the desktop).
As a result, iOS app receives the event correctly while it runs in the foreground.

But the following case is not.
When the user uses the iPhone browser app, Safari,(when iOS app runs in the background), I can't receive the event.(for example, client_joinconf function is not called).

channel.bind(eventName: "client-joinconf", callback: {
         (data: Any?) -> Void in self.client_joinconf(data: data)
})

Is it possible to receive the event when iOS app runs in the background?
Is there any alternative way for pusher service?

**Comment by hamchapman** [comment]
As previously mentioned, making Pusher's websocket service work in the background is not really a viable option.

Native push notifications are your only real option for getting data to an app that is not guaranteed to be in the foreground.

**Comment by gaozhan1991** [comment]
I've seen one example, that uses push notification, in the blog.
https://blog.pusher.com/how-to-send-ios-10-notifications-using-the-push-notifications-api/
May I refer this one?

**Comment by hamchapman** [comment]
Yep that's a good place to start. You can always find more information in our docs as well: https://pusher.com/docs/push_notifications/ios

**Comment by gaozhan1991** [comment]
Thanks for your support.
Well, when will the version for watchOS be released?
This is positively necessary.

**Comment by gaozhan1991** [comment]
Hi, do you have any updates of this package?

**Comment by taher-mosbah** [comment]
@hamchapman any updates on watchOS support ?

**Comment by hamchapman** [comment]
I'm not working on this currently but I know that Starscream does now have watchOS support.

This should make it easy enough for someone to make a pull request to add watchOS support.

**Comment by taher-mosbah** [comment]
@hamchapman thanks for your answer, I started playing with the lib but I noticed that Reachability.swift and TaskQueue does not support watchOS, do you see a workaround ? or should we refactor the code to not use those frameworks `#if os(watchOS)` ?

**Comment by danielrbrowne** [comment]
This is still relevant.

**Comment by CityTransit** [comment]
I can confirm that since #313 was introduced the library is functional on Apple Watch.

#350 enables the deployment target for Cocoapod consumers.
