### ISSUE TITLE
Can't subscribe to channel after upgrading from version 3.2.0 to 5.0.1

### ISSUE THREAD

**Issue by flagbug** [pusher/pusher-websocket-swift#154]
### What is the issue?

After upgrading the library from version 3.2.0 to 5.0.1, Pusher doesn't connect to a channel anymore

### Is it a crash report? Submit stack traces or anything that you think would help

This is the code I'm using:

```swift
class ConnectionService {
	
	public func connect() {
		let options = PusherClientOptions(
			authMethod: AuthMethod.authRequestBuilder(authRequestBuilder: PusherAuthRequestBuilder())
		)
	
		let pusher = Pusher(key: "thekey", options: options)
		pusher.connect()
		
		let myChannel = pusher.subscribe(channelName)
				
		let _ = myChannel.bind(eventName: "channel name", callback: { data in
                    // Do stuff with the data
		})
	}
}

class PusherAuthRequestBuilder: AuthRequestBuilderProtocol {
	func requestFor(socketID: String, channelName: String) -> URLRequest? {
		let path = String(format: "https://ourendpoint/auth?socket_id=%@&channel_name=%@", socketID, channelName).addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!
		var request = URLRequest(url: URL(string: path)!)
		request.httpMethod = "POST"
		
		let jwt = AccessTokenService.shared.IDToken!
		request.addValue("Bearer \(jwt)", forHTTPHeaderField: "Authorization")
		return request
	}
}
```

...

---- 

I see that the `pusher.subscribe` method is executed, but when I go into the debug console in the Pusher web UI, the channel is never subscribed to.
What's also interesting is that the `requestFor` method is never being hit;

CC @pusher/mobile

**Comment by hamchapman** [comment]
If you implement the `debugLog` part of the `ConnectionDelegate` and then try running the app, what logging output do you get? https://github.com/pusher/pusher-websocket-swift#connection-delegate

Thanks!

**Comment by flagbug** [comment]
@hamchapman The only thing that's printed is `[PUSHER DEBUG] Network reachable`, nothing more

**Comment by hamchapman** [comment]
It could be that `pusher` is being deallocated and therefore no connection or subscriptions are made before it is deallocated. 

You need to retain the `pusher` object somewhere, e.g. in a class property.

**Comment by flagbug** [comment]
@hamchapman Yep, that was the problem! Interesting that this has worked before, thanks!

**Comment by hamchapman** [comment]
No worries - I think it was a change in PusherSwift 4.0.0 and upwards (https://github.com/pusher/pusher-websocket-swift/issues/109)

It fixed a memory leak but meant that some usage behaviour from before, where the `Pusher` object wasn't explicitly being retained, broke.

Glad it's fixed!

**Comment by mayuritalaviya-nv** [comment]
i am also face same issue. When my pusher.connect() method calling then i am getting message in log :  

 "Your Pusher instance has probably become deallocated. See https://github.com/pusher/pusher-websocket-swift/issues/109 for more information" 

When I am upgrading from version 3.2.0 to 5.0.1 and facing this issue 

how to fix this issue ?

**Comment by hamchapman** [comment]
As above, you just need to make sure that you're retaining the `Pusher` object somewhere.

So if you create your `Pusher` object in a `ViewController` then you'd want to have a property that is something like:

```swift
class ViewController: UIViewController {

    var pusher: Pusher! = nil

    override func viewDidLoad() {
        super.viewDidLoad()
        pusher = Pusher(key: "YOUR_APP_KEY", options: optionsWithEndpoint)
        ...

```

**Comment by mayuritalaviya-nv** [comment]
@hamchapman 👍
