### ISSUE TITLE
Integration in Swift Server on Linux

### ISSUE THREAD

**Issue by drewmccormack** [pusher/pusher-websocket-swift#156]
I have a Kitura based server running on Heroku (Linux). Setting up push notifications there has proved very challenging, because Heroku don't have HTTP/2 yet. I am tempted to use a service like Pusher instead, but that would mean that I need this project to run on Linux. Has that been tested?

**Comment by hamchapman** [comment]
This library is for the iOS / macOS component, i.e. the client that received the push notifications. To trigger push notifications using the Pusher push notifications service you’ll want to send a request to our HTTP endpoint: https://pusher.com/docs/push_notifications/reference/server_api

We don’t currently have a Swift HTTP client to publish new push notifications but if this is something that you’d be interested in then we can certainly take a look at creating one, seeing as it’s not too difficult. On that note you may well find that you’re able to easily make the necessary requests yourself using URLSession or similar.

**Comment by drewmccormack** [comment]
Ah, OK. Thought it might be capable of posting events as well. I will look into just doing http requests from the server.
