### ISSUE TITLE
iOS quick start

### ISSUE THREAD

**Issue by laohanme** [pusher/pusher-websocket-swift#157]
### What is the issue?
I am a new user using pusherswift, when I follow iOS quick start tutorial it getting this problem
how to I fix?

your pusher instance has probably become deallocated. See https://github.com/pusher/pusher-websocket-swfit/issues/109 for more information

... 

### Is it a crash report? Submit stack traces or anything that you think would help

...

### Any improvements you suggest

...

---- 

CC @pusher/mobile

**Comment by hamchapman** [comment]
As the logging and the issue suggest you need to make sure that your `Pusher` instance doesn't become deallocated. That means you need to keep a reference to it somewhere. This will likely mean keeping a reference to it in your `ViewController` or in your `AppDelegate`, basically where you create your `Pusher` instance.

**Comment by hamchapman** [comment]
Closing as I'm assumed it's fixed. Let me know if you're still hitting problems. Thanks!

**Comment by azziwarlock21** [comment]
How would I keep a reference of it?
