### ISSUE TITLE
PusherSwift Not Compile in XCode 8.3 & Swift 3.3

### ISSUE THREAD

**Issue by starsoheil2007** [pusher/pusher-websocket-swift#158]
### What is the issue?
I have trouble by adding PusherSwift in compile .
Please help me to use this library. 
My Pod is :
`  pod 'PusherSwift',  :git => 'https://github.com/pusher/pusher-websocket-swift.git'`

Errors is : 
`Expected declaration . @_specialize(where T == UInt8)`

And 47 some error 

CC @pusher/mobile

**Comment by hamchapman** [comment]
Try this in your `Podfile` instead:

```
pod 'PusherSwift', '~> 4.2.1'
```

**Comment by hamchapman** [comment]
Assuming that this is fixed. Let me know if not!
