### ISSUE TITLE
Pusher doesn't reconnect when network is disconnected for ~5 min

### ISSUE THREAD

**Issue by roshanr95** [pusher/pusher-websocket-swift#171]
### What is the issue?

Pusher doesn't reconnect when network is disconnected for ~5 min.

Steps to reproduce:
1. Connect to Pusher and subscribe to channel. Events are received as usual.
2. Turn off Wifi for ~5 min.
3. Turn on Wifi.

What I can observe is that there is a Disconnection message in the web console once Wifi is turned on, but in the app, `pusher.connection.connectionState` still returns `connected` and `pusher.connection.socketId` returns the disconnected(as seen in the web console) socket id.
It works fine if Wifi is turned off for less than 2-3 min - it auto reconnects and receives events again, it's only an issue when it's disconnected for ~5 min or more.

I've also added
```
        pusher.connection.reconnectAttemptsMax = nil
        pusher.connection.maxReconnectGapInSeconds = 60
```
but it doesn't change anything.

I've also added a listener on `changedConnectionState`, but the only time it fires is during the initial connection setup - it goes from `connecting` to `connected`.

From what I can gather, there may be an error in state management which doesn't record the connection as disconnected. Or maybe there's some limit that is getting hit somewhere when disconnected for too long and Pusher stops retrying.

Looks similar to #170(might be because of same issue), but different observations. In my case, the Pusher client doesn't actually disconnect and reconnect(or at least it isn't reflected in `changedConnectionState`) even though the device does.

CC @pusher/mobile

**Comment by hamchapman** [comment]
Thanks for the detailed report! It definitely seems like this is similar to #170 and the state management side of things looks like a likely suspect. 

I'm not going to be able to take a look at this today but will hopefully be able to try and get a reproducible case running locally tomorrow.

**Comment by hamchapman** [comment]
I was able to reproduce this - thanks for the info!

You should be able to try the `cleanup-crash-fix` branch (associated PR here: https://github.com/pusher/pusher-websocket-swift/pull/178)

This should have fixed this problem. 

Let me know if you're able to and what results you see 👍  I'm hoping to merge that PR and release 6.0.0 on Monday if all goes well.
