### ISSUE TITLE
I'm not able to use "-" in channel name but it's allowed to use in java

### ISSUE THREAD

**Issue by MahendraRaj** [pusher/pusher-websocket-swift#172]
I'm trying to use the channel name "private-id", but I get an error saying
**Error authorizing channel [private-215474]: Optional("{\"detail\":\"Method \\\"GET\\\" not allowed.\"}")**

is it possible to use "-" in channel name in swift or am I implementing wrong?

CC @pusher/mobile

**Comment by hamchapman** [comment]
@MahendraRaj that sounds like an error coming from your server's auth endpoint. 

How have you implemented your auth in the Swift code?

**Comment by MahendraRaj** [comment]
Thank you @hamchapman  :)

**I have the issue fixed on my end as it was the error in the server api's header fields.**

Since the issue is fixed, I would close this issue
