### ISSUE TITLE
Conflict with Starscream

### ISSUE THREAD

**Issue by jethmalani** [pusher/pusher-websocket-swift#174]
### What is the issue?

I have Starscream installed and my Starscream methods don't work when I have the latest version of pusher installed in my project. I have to use version `pod 'PusherSwift', '5.0.1'` for it to work.  I am getting errors that says use of undeclared type 'websocket' when I have the latest version of pusher. 

I know you have bundled the contents of Starscream in your library. When I tried to remove Starscream from my project, it still doesn't work. It says No such module 'Starscream' near the import statement. 

The only way it kind of works is if remove all my `import Starscream` and replace them with `import PusherSwift`. But even then there are delegate methods in Starscream that are not recognized. 

... 

### Is it a crash report? Submit stack traces or anything that you think would help
No crashing
...

### Any improvements you suggest
n/a
...

---- 

CC @pusher/mobile

**Comment by hamchapman** [comment]
@jethmalani [5.1.1](https://github.com/pusher/pusher-websocket-swift/blob/master/CHANGELOG.md#511---2018-01-22) bumped the version of Starscream to 3+ and that's when the interface for it changed, see https://github.com/daltoniam/Starscream/blob/master/CHANGELOG.md#300.

Do you have a project you could share that exhibits the errors / problems that you've described? That would make it much easier for me to debug things.

I'm considering explicitly defining the dependencies to make things like this easier, although it would make the resulting framework larger, by quite a considerable margin, and I'm not sure the pros outweigh the cons.

**Comment by jethmalani** [comment]
I think explicitly defining the dependencies makes sense. Unfortunately, I don't have a project that displays the issue. But I am using the delegate methods in Starscream like this: 

    `func websocketDidConnect(socket: WebSocketClient) {
        print("websocket is connected")
    }`

These delegate methods are creating the issue. 

I don't know about other dependencies that you are using but Starscream isn't that big.

**Comment by mohammdsss1** [comment]
<img width="1101" alt="screen shot 2018-03-07 at 2 07 10 pm" src="https://user-images.githubusercontent.com/7831855/37091496-12f0b9c6-2211-11e8-84d4-bf4974eda677.png">

**Comment by hamchapman** [comment]
Hey @jethmalani what do you use for dependency management? If you use Carthage then you could try using the branch I just pushed `proper-dependencies` (PR is here: https://github.com/pusher/pusher-websocket-swift/pull/175)

It won't work if you're using Cocoapods just yet, but that should be working soon too 👍

**Comment by jethmalani** [comment]
I do use cocoa pods. I will wait until it is ready for cocoa pods then. Thanks!

**Comment by hamchapman** [comment]
You should be able to try try the `cleanup-crash-fix` branch (associated PR here: https://github.com/pusher/pusher-websocket-swift/pull/178)

This should have fixed this problem. 

Let me know if you're able to and what results you see 👍  I'm hoping to merge that PR and release 6.0.0 on Monday if all goes well.
