### ISSUE TITLE
Using PusherSwift.framework in Xcode gives "Using Module compiled with Swift 4.0 cannot be imported in Swift 4.0.3"

### ISSUE THREAD

**Issue by dennybiasiolli** [pusher/pusher-websocket-swift#177]
### What is the issue?

I've downloaded, extracted and used latest version of `PusherSwift.framework` (5.1.1).
When I use `PusherSwift` in Xcode it gives me this error

> Using Module compiled with Swift 4.0 cannot be imported in Swift 4.0.3

at line with

`import PusherSwift`

Is it possible to update this framework using latest version of Swift?

### Any improvements you suggest

I've fixed this problem with the following steps:

1) Install [Carthage](https://github.com/Carthage/Carthage)

    `brew install carthage`

2) Create a Cartfile with the following content

    `github "pusher/pusher-websocket-swift" >= 5.1.1`

3) Run `carthage update`. This will fetch dependencies into a Carthage/Checkouts folder and build each one or download a pre-compiled framework.

3) Use updated module in `Carthage/Build/` folder

---- 

CC @pusher/mobile

**Comment by hamchapman** [comment]
You'll want to run `carthage update --no-use-binaries` and then whatever version of Swift you're using locally (4.0.3) will be used to build the framework
