### ISSUE TITLE
forceTimeout should be set when disconnecting from reachability event

### ISSUE THREAD

**Issue by hamchapman** [pusher/pusher-websocket-swift#180]
### What is the issue?

See title

https://github.com/pusher/pusher-websocket-swift/blob/master/Sources/PusherConnection.swift#L372

should accept a `forceTimeout` parameter.

This should then call down into `self.socket.disconnect()` with `forceTimeout` passed on.

See https://github.com/daltoniam/Starscream/issues/401#issuecomment-345062141

---- 

CC @pusher/mobile

**Comment by danielrbrowne** [comment]
No longer relevant as this SDK doesn't use Starscream any more.
