### ISSUE TITLE
It's not connected when I go from background to foreground.

### ISSUE THREAD

**Issue by miuyor** [pusher/pusher-websocket-swift#182]
### What is the issue?

When my application gets into the background, it breaks the connection.But when I entered the foreground the connection was still broken.It can be reconnected for a short time from the background, but not for a long time. I work with Objective-C.

... 

### Is it a crash report? Submit stack traces or anything that you think would help

...

### Any improvements you suggest

...

---- 

CC @pusher/mobile

**Comment by Vincent-CDeng** [comment]
i experienced the same problem ,can i  manually reconnect? i did set autoReconnect to YES ,
but it failed to reconnect when the app enter from background (stayed in background for about 30 minutes ).  i called connect method in  applicationWillEnterForeground . but it doesn't work.
