### ISSUE TITLE
I can't bind to a channel event on iOS(Swift), but works on Android

### ISSUE THREAD

**Issue by MoShaikhon** [pusher/pusher-websocket-swift#183]
### What is the issue?
It's basically what the title says, I'm trying to bind to a channel event, but it's not working on iOS, only on Android.
my bind code in Swift
![bind](https://user-images.githubusercontent.com/26471845/39093256-95f4147e-461c-11e8-8775-4042a4917ae4.png)
. 
the debug logs show that the pusher connection and channel subscription are working fine. 
![logs](https://user-images.githubusercontent.com/26471845/39093257-96216208-461c-11e8-8f14-e115eaac17af.png)

... 

### Is it a crash report? Submit stack traces or anything that you think would help

...

### Any improvements you suggest

...

---- 

CC @pusher/mobile

**Comment by jameshfisher** [comment]
Hi @MoShaikhon - thanks for the report. I don't think the report provides enough information to debug the issue - I would need steps to reproduce, a description of the behavior you expected, and a description of the behavior you saw. If you can provide this, please re-open. If the report is sensitive, you can go via [support](https://support.pusher.com/hc/en-us).

**Comment by MoShaikhon** [comment]
Sorry for not being descriptive enough, it's just because I haven't done much, I only copied and pasted snippets of the docs code, putting in the key, channel, and the event I was trying to bind to. I used the debug log and this is what I got: 
![code](https://user-images.githubusercontent.com/26471845/39180713-e9a79c3e-47b7-11e8-80df-9506bfa51f41.png)
![debug](https://user-images.githubusercontent.com/26471845/39180714-e9d8a702-47b7-11e8-9780-7c2883ec8dfe.png)
![debug 2](https://user-images.githubusercontent.com/26471845/39180716-ea0bd58c-47b7-11e8-9e12-eb205096394e.png)
![logs](https://user-images.githubusercontent.com/26471845/39180717-ea3d2fec-47b7-11e8-9bad-2be7c92dc384.png)

**Comment by hamchapman** [comment]
That all looks like it's working as expected. 

Are you hitting an error?

How are you sending an event to the channel? Is it never received?

**Comment by MoShaikhon** [comment]
I'm not getting any errors.
Well, my friend tried binding to that same channel (on Android) and he's receiving events as expected, which is why it baffles me.

**Comment by hamchapman** [comment]
How are you sending events? Are you using the same Pusher app ID etc?
