### ISSUE TITLE
'WebSocketClient' is ambiguous for type lookup in this context

### ISSUE THREAD

**Issue by shaharukhs** [pusher/pusher-websocket-swift#184]
### Steps to reproduce

What must I do to reproduce the bug?

### Expected behavior

What did you expect to happen?

### Actual behavior

What actually happened? Submit stack traces or anything that you think would help.

In my project from past I am using `Starscream` for Web Sockets and now when I try to implement `PusherSwift` in my project/same viewcontroller it is giving me following error  

> 'WebSocketClient' is ambiguous for type lookup in this context

```
Using PusherSwift (5.1.1)
Using Starscream (3.0.5)
```

### Any improvements you suggest

...

**Comment by hamchapman** [comment]
Update to PusherSwift 6.0.0 and this error shouldn't occur

**Comment by shaharukhs** [comment]
Now I am getting bellow error

```
/Pods/StarscreamFork/zlib/module.modulemap:1:8: error: redefinition of module 'SSCZLib'
module SSCZLib [system] {
       ^
/Pods/Starscream/zlib/module.modulemap:1:8: note: previously defined here
module SSCZLib [system] {
       ^
/Pods/StarscreamFork/zlib/module.modulemap:6:8: error: redefinition of module 'SSCommonCrypto'
module SSCommonCrypto [system] {
       ^
/Pods/Starscream/zlib/module.modulemap:6:8: note: previously defined here

module SSCommonCrypto [system] {
       ^
<unknown>:0: error: could not build Objective-C module 'CryptoSwift'
```

```

Using CryptoSwift (0.9.0)
Using PusherSwift (6.0.0)
Using Starscream (3.0.5)
Using StarscreamFork (3.0.6)
```

**Comment by hamchapman** [comment]
Ah yes, we need to merge https://github.com/pusher/pusher-websocket-swift/pull/181

@jameshfisher this could be a good time for me to run through the release process 😁

**Comment by shaharukhs** [comment]
I have to implement pusher in my project so can you have any solutions ?
