### ISSUE TITLE
Cannot receive messages on a channel while app is in applicationDidEnterBackground state

### ISSUE THREAD

**Issue by Fyb3roptik** [pusher/pusher-websocket-swift#186]
### Steps to reproduce

What must I do to reproduce the bug? Create an app with pusher and then run it, then turn the screen off. Messages are still not coming through while applicationDidEnterBackground is triggered

### Expected behavior

What did you expect to happen? I expect messages to still come through!

### Actual behavior

What actually happened? No message are coming through

**Comment by TomKemp** [comment]
I'm going to close this issue as it's quite old. Sorry that you didn't get a reply.

It isn't possible to maintain a websocket connection when an app is in the background unfortunately, therefore messages can't be received. You could fallback to using push notifications while your app is in the background.
