### ISSUE TITLE
Crash: NSOperationQueue (QOS: UNSPECIFIED) EXC_BAD_ACCESS KERN_INVALID_ADDRESS

### ISSUE THREAD

**Issue by mohammdsss1** [pusher/pusher-websocket-swift#187]
### Steps to reproduce
N/A

What must I do to reproduce the bug?
I didn't encounter the crash myself, its reported from the customers on the production version.

### Expected behavior

What did you expect to happen?
Not crash 

### Actual behavior

What actually happened? Submit stack traces or anything that you think would help.
I didn't encounter the crash myself, its reported from the customers on the production version.
Here is the stack trace:

Crashed: NSOperationQueue 0x1c803b880 (QOS: UNSPECIFIED)
0  CoreFoundation                 0x18291edc8 _CFRetain + 124
1  StarscreamFork                 0x1018f8cf4 protocol witness for WSStream.write(data:) in conformance FoundationStream (WebSocket.swift:237)
2  StarscreamFork                 0x1018fe5dc closure #1 in WebSocket.dequeueWrite(_:code:writeCompletion:) (WebSocket.swift:1263)
3  StarscreamFork                 0x1018f6f64 _T0Ieg_IeyB_TR (WebSocket.swift)
4  Foundation                     0x183486e88 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 16
5  Foundation                     0x1833c88d0 -[NSBlockOperation main] + 72
6  Foundation                     0x1833c7cac -[__NSOperationInternal _start:] + 848
7  Foundation                     0x18348876c __NSOQSchedule_f + 404
8  libdispatch.dylib              0x182350ae4 _dispatch_client_callout + 16
9  libdispatch.dylib              0x182358f18 _dispatch_continuation_pop$VARIANT$mp + 424
10 libdispatch.dylib              0x182357850 _dispatch_async_redirect_invoke$VARIANT$mp + 604
11 libdispatch.dylib              0x18235dd30 _dispatch_root_queue_drain + 588
12 libdispatch.dylib              0x18235da80 _dispatch_worker_thread3 + 120
13 libsystem_pthread.dylib        0x182683fac _pthread_wqthread + 1176
14 libsystem_pthread.dylib        0x182683b08 start_wqthread + 4

This crash happens on rare occasions.

**Comment by ct222** [comment]
Starscream 3.1.0 已解决这个问题。pusher 啥时候更新应用库？

**Comment by TomKemp** [comment]
I'm going to close this issue because the Starscream version has been updated since this issue was opened.
