### ISSUE TITLE
Build failed: CryptoSwift issues

### ISSUE THREAD

**Issue by valerymadiedo** [pusher/pusher-websocket-swift#189]
### Description

Hello,
I'm trying to use PusherSwift but after installing it with cocoapods and building Im getting "CryptoSwift 25 issues". I have cleaned and build the proyect but I keep getting the same errors. I'm really new into Swift so I don't really know how to resolve this issue.

### Steps to reproduce
pod 'PusherSwift' into podfile
pod install
import PusherSwift into a file and build

### Error logs
![screen shot 2018-05-29 at 3 23 01 pm](https://user-images.githubusercontent.com/33358768/40683438-381671da-6354-11e8-8826-3e082d9853e1.png)

### Versions
Xcode 9.2 
Swift 4.0
CryptoSwift (0.9.0)
PusherSwift (6.1.0)
ReachabilitySwift (4.1.0)
Starscream (3.0.5)
TaskQueue (1.1.1)

**Comment by MikeSilvis** [comment]
I'm also getting a similar issue when using Carthage, relating to CryptoSwift 

`module file's minimum deployment target is ios9.0 v9.0`

**Comment by Vinzius** [comment]
Hi,

I think the latest version isn't compatible with your Xcode version.

Check this related issue: https://github.com/pusher/pusher-websocket-swift/issues/185

Cheers,
Vincent

**Comment by valerymadiedo** [comment]
Hello @Vinzius, thanks a lot for your comment, I tried with version PusherSwift 5.1.1 and is compatible with my xcode.
