### ISSUE TITLE
No such module Starscream

### ISSUE THREAD

**Issue by machive** [pusher/pusher-websocket-swift#191]
I'm trying to build my app under XCode 9.4.1 and am getting an error "No such module ''Starscream'" in the PusherWebsocketDelegate 2.swift file. I updated the Podfile and set the platform to 11.3 which is my iOS deployment target. I did a pod update but I am still getting this error. It shows I am using PusherSwift 5.1.1

  Any ideas how to fix this problem?

**Comment by hamchapman** [comment]
Are you able to update to 6.1.0?

**Comment by machive** [comment]
Yes, I did that, fixed up some version issues with Reachability, and got it to build. 

Unfortunately, the app will no longer distribute through Fabric. Fabric hangs up on the release notes screen and will not go forward. Perhaps that is a Fabric problem. 

Thanks for the help! Much appreciated.

**Comment by hamchapman** [comment]
Let us know if it appears to be a problem with this library and we can help debug 👍

**Comment by hamchapman** [comment]
Closing as I'm assuming it's all working fine for you now. Let us know if not.
