### ISSUE TITLE
How to HttpAuthorizer in swift 4  and PusherClientOptions multiple parameter

### ISSUE THREAD

**Issue by PrakashMuralikannan** [pusher/pusher-websocket-swift#193]
i used xcode 9.4 swift 4. in android they have like this code for authentication
         PusherOptions options = new PusherOptions();
         HttpAuthorizer authorizer = new HttpAuthorizer("hhttp://sample/api/");
         authorizer.setHeaders(headers);
         options.setCluster("ap2").setAuthorizer(authorizer);
         Pusher pusher = new Pusher("App_Key", options);
         Channel channel = pusher.subscribePrivate("private-user_chat.")

How to implement this in swift??? 
without add the headers i cannot able to get any logs in pusher debug log.

**Comment by PrakashMuralikannan** [comment]
let options = PusherClientOptions(
                authMethod: AuthMethod.authRequestBuilder(authRequestBuilder: AuthRequestBuilder()),
                host: .cluster("ABC")
            )
        pusher = Pusher(
            key: "XXXXXYZZZ123",
            options: options
        )
        pusher.delegate = self
        pusher.connect()




class AuthRequestBuilder: AuthRequestBuilderProtocol {
    func requestFor(socketID: String, channelName: String) -> URLRequest? {
        var request = URLRequest(url: URL(string: "https://zxczczc.com/auth")!)
        request.httpMethod = "POST"
        request.httpBody = "socket_id=\(socketID)&channel_name=\(channelName)".data(using: String.Encoding.utf8)
        request.setValue( "access_token", forHTTPHeaderField: "Authorization")
        return request
        
    }
}

**Comment by kcw-grunt** [comment]
This is working for me:

``` 
let options = PusherClientOptions(authMethod: 
    .endpoint(authEndpoint:"https://mypusherauthendpoint"), attemptToReturnJSONObject: true, 
    autoReconnect: true, encrypted: true, activityTimeout: 10)
            pusherClient = Pusher(withAppKey: "XXXXXXXXXXXX" options: options)
            pusherClient.delegate = self
            pusherClient.connect()
```
In this case the   func:

```
func debugLog(message: String) {
        print("PUSHER DELEGATE LOG: \(message)")
    } 
```
callback sends messages.

**Comment by TomKemp** [comment]
I'm going to close this issue now, but please let me know if you're still having problems.

**Comment by najeeburrehman-brainx** [comment]
Any update on this I also want to do the same as mentioned in Issue. But can't find anything to work. I tried with authMethod `AuthRequestBuilder` and tried with code that @PrakashMuralikannan suggested but no luck.
Any help would be appreciated.

**Comment by kyweng** [comment]
Hi,

May I know why it will receive this error message even passing with the cluster?

[PUSHER DEBUG] websocketDidReceiveMessage {"event":"pusher:error","data":{"code":4001,"message":"App key XXXXX not in this cluster. Did you forget to specify the cluster?"}}

This is my code:
let options = PusherClientOptions(
                authMethod: AuthMethod.authRequestBuilder(authRequestBuilder: AuthRequestBuilder()),
                host: .cluster("xxx")
            )

And Android is using the same cluster and its work. But iOS Swift is not working at all. Someone can guide me on this? Thanks.

**Comment by danielrbrowne** [comment]
@kyweng I am assuming that "xxx" is a dummy value for your app's cluster. I would in the first instance check that you don't have a typo in either your app key or your cluster name.

This issue is old and has been closed. It also looks like your query isn't directly related to the original question in this issue. Feel free to contact support@pusher.com with more general queries that aren't feature requests or bug reports.
