### ISSUE TITLE
changedConnectionState: is never called in objective-c 

### ISSUE THREAD

**Issue by gnikolas** [pusher/pusher-websocket-swift#196]
Have embedded pusher-websocket-swift Library in my Objective-c project and the changedConnectionState is never called (for example when the app goes offline)
Any idea why this is happen in Objective-c?

**Comment by ay8s** [comment]
Seeing the same also. Will try and take a look later.

**Comment by ay8s** [comment]
Forgot to set the delegate Doh.

**Comment by TomKemp** [comment]
I tried this myself and it seems to work fine. I'm going to close this issue as it's old, but if you're still having problems then let me know.
