### ISSUE TITLE
Crash at specialized FoundationStream.connect(url:port:timeout:ssl:completion:)

### ISSUE THREAD

**Issue by mohammdsss1** [pusher/pusher-websocket-swift#197]
### Steps to reproduce

What must I do to reproduce the bug?
It happened on the client side, thus I have no clue what are the steps, plus I didn't encounter that crash myself. 

### Expected behavior

What did you expect to happen?
Not crash

### Actual behavior

What actually happened? Submit stack traces or anything that you think would help.
# Crashlytics - plaintext stacktrace downloaded by Mohammad Salah at Sun, 28 Oct 2018 11:50:29 GMT
# URL: https://fabric.io/sit-mena/ios/apps/com.posrocket.registeripadv2/issues/5b93fcb26007d59fcd14ff02/sessions/2ad6c9d75d5c4351a4f9436715e5d56c_DNE_0_v2?
# Organization: Sit Mena
# Platform: ios
# Application: POSRocket
# Version: 2.8 (3)
# Bundle Identifier: com.posrocket.registeripadv2
# Issue #: 348
# Issue ID: 5b93fcb26007d59fcd14ff02
# Session ID: 2ad6c9d75d5c4351a4f9436715e5d56c_DNE_0_v2
# Date: 2018-09-23T20:00:00Z
# OS Version: 11.4.0 (15F79)
# Device: iPad Air
# RAM Free: 1.9%
# Disk Free: 19.8%

#0. Crashed: com.apple.main-thread
0  libdispatch.dylib              0x180f349e0 _dispatch_Block_copy + 48
1  libdispatch.dylib              0x180f3d198 dispatch_async$VARIANT$mp + 64
2  libdispatch.dylib              0x180f3d198 dispatch_async$VARIANT$mp + 64
3  libswiftDispatch.dylib         0x10303d2dc (Missing)
4  Starscream                     0x102aafb6c specialized FoundationStream.connect(url:port:timeout:ssl:completion:) (WebSocket.swift:212)
5  Starscream                     0x102aa0eb8 protocol witness for WSStream.connect(url:port:timeout:ssl:completion:) in conformance FoundationStream (WebSocket.swift)
6  Starscream                     0x102ab37e8 specialized WebSocket.initStreamsWithData(_:_:) (WebSocket.swift:660)
7  Starscream                     0x102aa3e00 WebSocket.createHTTPRequest() (WebSocket.swift:612)
8  PusherSwift                    0x10244a2e8 PusherConnection.connect() (PusherConnection.swift:301)
9  PusherSwift                    0x10244af24 @objc PusherConnection.unsubscribeAll() + 4329172772
10 Foundation                     0x18208f3d4 __NSFireTimer + 88
11 CoreFoundation                 0x1815ebaa8 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 28
12 CoreFoundation                 0x1815eb76c __CFRunLoopDoTimer + 864
13 CoreFoundation                 0x1815eb010 __CFRunLoopDoTimers + 248
14 CoreFoundation                 0x1815e8b60 __CFRunLoopRun + 2168
15 CoreFoundation                 0x181508da8 CFRunLoopRunSpecific + 552
16 GraphicsServices               0x1834ed020 GSEventRunModal + 100
17 UIKit                          0x18b525758 UIApplicationMain + 236
18 POSRocket                      0x1012d9d38 main (DrawerPayMethod.swift:32)
19 libdyld.dylib                  0x180f99fc0 start + 4

--

#0. Crashed: com.apple.main-thread
0  libdispatch.dylib              0x180f349e0 _dispatch_Block_copy + 48
1  libdispatch.dylib              0x180f3d198 dispatch_async$VARIANT$mp + 64
2  libdispatch.dylib              0x180f3d198 dispatch_async$VARIANT$mp + 64
3  libswiftDispatch.dylib         0x10303d2dc (Missing)
4  Starscream                     0x102aafb6c specialized FoundationStream.connect(url:port:timeout:ssl:completion:) (WebSocket.swift:212)
5  Starscream                     0x102aa0eb8 protocol witness for WSStream.connect(url:port:timeout:ssl:completion:) in conformance FoundationStream (WebSocket.swift)
6  Starscream                     0x102ab37e8 specialized WebSocket.initStreamsWithData(_:_:) (WebSocket.swift:660)
7  Starscream                     0x102aa3e00 WebSocket.createHTTPRequest() (WebSocket.swift:612)
8  PusherSwift                    0x10244a2e8 PusherConnection.connect() (PusherConnection.swift:301)
9  PusherSwift                    0x10244af24 @objc PusherConnection.unsubscribeAll() + 4329172772
10 Foundation                     0x18208f3d4 __NSFireTimer + 88
11 CoreFoundation                 0x1815ebaa8 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 28
12 CoreFoundation                 0x1815eb76c __CFRunLoopDoTimer + 864
13 CoreFoundation                 0x1815eb010 __CFRunLoopDoTimers + 248
14 CoreFoundation                 0x1815e8b60 __CFRunLoopRun + 2168
15 CoreFoundation                 0x181508da8 CFRunLoopRunSpecific + 552
16 GraphicsServices               0x1834ed020 GSEventRunModal + 100
17 UIKit                          0x18b525758 UIApplicationMain + 236
18 POSRocket                      0x1012d9d38 main (DrawerPayMethod.swift:32)
19 libdyld.dylib                  0x180f99fc0 start + 4

#1. com.apple.uikit.eventfetch-thread
0  libsystem_kernel.dylib         0x1810a7e08 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1810a7c80 mach_msg + 72
2  CoreFoundation                 0x1815eae40 __CFRunLoopServiceMachPort + 196
3  CoreFoundation                 0x1815e8908 __CFRunLoopRun + 1568
4  CoreFoundation                 0x181508da8 CFRunLoopRunSpecific + 552
5  Foundation                     0x181f7d674 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 304
6  Foundation                     0x181f7d51c -[NSRunLoop(NSRunLoop) runUntilDate:] + 148
7  UIKit                          0x18b20a768 -[UIEventFetcher threadMain] + 136
8  Foundation                     0x18208defc __NSThread__start__ + 1040
9  libsystem_pthread.dylib        0x181269220 _pthread_body + 272
10 libsystem_pthread.dylib        0x181269110 _pthread_body + 290
11 libsystem_pthread.dylib        0x181267b10 thread_start + 4

#2. com.twitter.crashlytics.ios.MachExceptionServer
0  POSRocket                      0x1016be110 CLSProcessRecordAllThreads (CLSProcess.c:376)
1  POSRocket                      0x1016be110 CLSProcessRecordAllThreads (CLSProcess.c:376)
2  POSRocket                      0x1016be584 CLSProcessRecordAllThreads (CLSProcess.c:407)
3  POSRocket                      0x1016adbc4 CLSHandler (CLSHandler.m:26)
4  POSRocket                      0x1016a8ee8 CLSMachExceptionServer (CLSMachException.c:446)
5  libsystem_pthread.dylib        0x181269220 _pthread_body + 272
6  libsystem_pthread.dylib        0x181269110 _pthread_body + 290
7  libsystem_pthread.dylib        0x181267b10 thread_start + 4

#3. RLMRealm notification listener
0  libsystem_kernel.dylib         0x1810ac34c kevent + 8
1  Realm                          0x1024dfaec realm::_impl::ExternalCommitHelper::listen() (external_commit_helper.cpp:203)
2  Realm                          0x1024e0564 std::__1::__async_func<realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0>::operator()() (future:2323)
3  Realm                          0x1024e04ec std::__1::__async_assoc_state<void, std::__1::__async_func<realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0> >::__execute() (future:1041)
4  Realm                          0x1024e069c std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (std::__1::__async_assoc_state<void, std::__1::__async_func<realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0> >::*)(), std::__1::__async_assoc_state<void, std::__1::__async_func<realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0> >*> >(void*, void*) (memory:2549)
5  libsystem_pthread.dylib        0x181269220 _pthread_body + 272
6  libsystem_pthread.dylib        0x181269110 _pthread_body + 290
7  libsystem_pthread.dylib        0x181267b10 thread_start + 4

#4. com.apple.CFStream.LegacyThread
0  libsystem_kernel.dylib         0x1810a7e08 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1810a7c80 mach_msg + 72
2  CoreFoundation                 0x1815eae40 __CFRunLoopServiceMachPort + 196
3  CoreFoundation                 0x1815e8908 __CFRunLoopRun + 1568
4  CoreFoundation                 0x181508da8 CFRunLoopRunSpecific + 552
5  CoreFoundation                 0x1815fa074 _legacyStreamRunLoop_workThread + 268
6  libsystem_pthread.dylib        0x181269220 _pthread_body + 272
7  libsystem_pthread.dylib        0x181269110 _pthread_body + 290
8  libsystem_pthread.dylib        0x181267b10 thread_start + 4

#5. com.apple.NSURLConnectionLoader
0  libsystem_kernel.dylib         0x1810a7e08 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1810a7c80 mach_msg + 72
2  CoreFoundation                 0x1815eae40 __CFRunLoopServiceMachPort + 196
3  CoreFoundation                 0x1815e8908 __CFRunLoopRun + 1568
4  CoreFoundation                 0x181508da8 CFRunLoopRunSpecific + 552
5  CFNetwork                      0x181e166e0 -[__CoreSchedulingSetRunnable runForever] + 220
6  Foundation                     0x18208defc __NSThread__start__ + 1040
7  libsystem_pthread.dylib        0x181269220 _pthread_body + 272
8  libsystem_pthread.dylib        0x181269110 _pthread_body + 290
9  libsystem_pthread.dylib        0x181267b10 thread_start + 4

#6. Logentries
0  libsystem_kernel.dylib         0x1810a7e08 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1810a7c80 mach_msg + 72
2  CoreFoundation                 0x1815eae40 __CFRunLoopServiceMachPort + 196
3  CoreFoundation                 0x1815e8908 __CFRunLoopRun + 1568
4  CoreFoundation                 0x181508da8 CFRunLoopRunSpecific + 552
5  Foundation                     0x181f7d674 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 304
6  Foundation                     0x181ff21a8 -[NSRunLoop(NSRunLoop) run] + 88
7  POSRocket                      0x1012d51e0 -[LEBackgroundThread main] (LEBackgroundThread.m:379)
8  Foundation                     0x18208defc __NSThread__start__ + 1040
9  libsystem_pthread.dylib        0x181269220 _pthread_body + 272
10 libsystem_pthread.dylib        0x181269110 _pthread_body + 290
11 libsystem_pthread.dylib        0x181267b10 thread_start + 4

#7. com.apple.CFSocket.private
0  libsystem_kernel.dylib         0x1810c9538 __select + 8
1  CoreFoundation                 0x1815f3378 __CFSocketManager + 644
2  libsystem_pthread.dylib        0x181269220 _pthread_body + 272
3  libsystem_pthread.dylib        0x181269110 _pthread_body + 290
4  libsystem_pthread.dylib        0x181267b10 thread_start + 4

#8. RLMRealm notification listener
0  libsystem_kernel.dylib         0x1810ac34c kevent + 8
1  Realm                          0x1024dfaec realm::_impl::ExternalCommitHelper::listen() (external_commit_helper.cpp:203)
2  Realm                          0x1024e0564 std::__1::__async_func<realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0>::operator()() (future:2323)
3  Realm                          0x1024e04ec std::__1::__async_assoc_state<void, std::__1::__async_func<realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0> >::__execute() (future:1041)
4  Realm                          0x1024e069c std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (std::__1::__async_assoc_state<void, std::__1::__async_func<realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0> >::*)(), std::__1::__async_assoc_state<void, std::__1::__async_func<realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0> >*> >(void*, void*) (memory:2549)
5  libsystem_pthread.dylib        0x181269220 _pthread_body + 272
6  libsystem_pthread.dylib        0x181269110 _pthread_body + 290
7  libsystem_pthread.dylib        0x181267b10 thread_start + 4

#9. RLMRealm notification listener
0  libsystem_kernel.dylib         0x1810ac34c kevent + 8
1  Realm                          0x1024dfaec realm::_impl::ExternalCommitHelper::listen() (external_commit_helper.cpp:203)
2  Realm                          0x1024e0564 std::__1::__async_func<realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0>::operator()() (future:2323)
3  Realm                          0x1024e04ec std::__1::__async_assoc_state<void, std::__1::__async_func<realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0> >::__execute() (future:1041)
4  Realm                          0x1024e069c std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (std::__1::__async_assoc_state<void, std::__1::__async_func<realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0> >::*)(), std::__1::__async_assoc_state<void, std::__1::__async_func<realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0> >*> >(void*, void*) (memory:2549)
5  libsystem_pthread.dylib        0x181269220 _pthread_body + 272
6  libsystem_pthread.dylib        0x181269110 _pthread_body + 290
7  libsystem_pthread.dylib        0x181267b10 thread_start + 4

#10. Thread
0  libsystem_pthread.dylib        0x181267b04 start_wqthread + 122

#11. Thread
0  libsystem_kernel.dylib         0x1810c9d84 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x1812680a0 _pthread_wqthread + 1420
2  libsystem_pthread.dylib        0x181267b08 start_wqthread + 4

#12. Thread
0  libsystem_pthread.dylib        0x181267b04 start_wqthread + 122

#13. Thread
0  libsystem_kernel.dylib         0x1810c9d84 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x181267eb4 _pthread_wqthread + 928
2  libsystem_pthread.dylib        0x181267b08 start_wqthread + 4

#14. Thread
0  libsystem_kernel.dylib         0x1810c9d84 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x181267eb4 _pthread_wqthread + 928
2  libsystem_pthread.dylib        0x181267b08 start_wqthread + 4

#15. io.answers.EventQueue (QOS: BACKGROUND)
0  POSRocket                      0x1016d54ec __39-[ANSAnswersController setupFlushTimer]_block_invoke (ANSAnswersController.m:241)
1  Foundation                     0x181fac8d0 -[NSBlockOperation main] + 72
2  Foundation                     0x181fabcac -[__NSOperationInternal _start:] + 848
3  libdispatch.dylib              0x180f34a60 _dispatch_client_callout + 16
4  libdispatch.dylib              0x180f3c170 _dispatch_block_invoke_direct$VARIANT$mp + 224
5  libdispatch.dylib              0x180f34a60 _dispatch_client_callout + 16
6  libdispatch.dylib              0x180f3c170 _dispatch_block_invoke_direct$VARIANT$mp + 224
7  libdispatch.dylib              0x180f3c05c dispatch_block_perform$VARIANT$mp + 104
8  Foundation                     0x18206c750 __NSOQSchedule_f + 376
9  libdispatch.dylib              0x180f34a60 _dispatch_client_callout + 16
10 libdispatch.dylib              0x180f3ce94 _dispatch_continuation_pop$VARIANT$mp + 424
11 libdispatch.dylib              0x180f3b7cc _dispatch_async_redirect_invoke$VARIANT$mp + 604
12 libdispatch.dylib              0x180f41cac _dispatch_root_queue_drain + 588
13 libdispatch.dylib              0x180f419fc _dispatch_worker_thread3 + 120
14 libsystem_pthread.dylib        0x181267fac _pthread_wqthread + 1176
15 libsystem_pthread.dylib        0x181267b08 start_wqthread + 4

#16. Thread
0  libsystem_kernel.dylib         0x1810c9d84 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x1812680a0 _pthread_wqthread + 1420
2  libsystem_pthread.dylib        0x181267b08 start_wqthread + 4

#17. Thread
0  libsystem_kernel.dylib         0x1810c9d84 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x181267eb4 _pthread_wqthread + 928
2  libsystem_pthread.dylib        0x181267b08 start_wqthread + 4

#18. Thread
0  libsystem_kernel.dylib         0x1810c9d84 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x181267eb4 _pthread_wqthread + 928
2  libsystem_pthread.dylib        0x181267b08 start_wqthread + 4

#19. com.apple.CFNetwork.addPersistCacheToStorageDaemon
0  CFNetwork                      0x181c3c638 __CFURLCache::logCacheEvent(CFURLCacheEventType, _CFURLRequest const*) + 42
1  libdispatch.dylib              0x180f34aa0 _dispatch_call_block_and_release + 24
2  libdispatch.dylib              0x180f34a60 _dispatch_client_callout + 16
3  libdispatch.dylib              0x180f3e9b4 _dispatch_queue_serial_drain$VARIANT$mp + 608
4  libdispatch.dylib              0x180f3f2fc _dispatch_queue_invoke$VARIANT$mp + 336
5  libdispatch.dylib              0x180f3fcc8 _dispatch_root_queue_drain_deferred_wlh$VARIANT$mp + 340
6  libdispatch.dylib              0x180f48098 _dispatch_workloop_worker_thread$VARIANT$mp + 668
7  libsystem_pthread.dylib        0x181267e70 _pthread_wqthread + 860
8  libsystem_pthread.dylib        0x181267b08 start_wqthread + 4

#20. Thread
0  libsystem_kernel.dylib         0x1810c9d84 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x1812680a0 _pthread_wqthread + 1420
2  libsystem_pthread.dylib        0x181267b08 start_wqthread + 4

#21. Thread
0  libsystem_kernel.dylib         0x1810c9d84 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x181267eb4 _pthread_wqthread + 928
2  libsystem_pthread.dylib        0x181267b08 start_wqthread + 4

### Any improvements you suggest

...

**Comment by TomKemp** [comment]
This appears to be an issue with Starscream which has been updated since you posted this issue. I'm going to close this issue but let me know if you're still experiencing crashes. Apologies that you didn't get a reply sooner.
