### ISSUE TITLE
dyld: Library not loaded:

### ISSUE THREAD

**Issue by 3viewgroup** [pusher/pusher-websocket-swift#2]
dyld: Library not loaded: @rpath/PusherSwift.framework/PusherSwift
  Referenced from: /private/var/mobile/Containers/Bundle/Application/CF93F176-154C-423D-B726-5ECD4DBB0CB9/iOS Example.app/iOS Example
  Reason: image not found

**Comment by hamchapman** [comment]
Is this still a problem for you?

I can't seem to recreate this issue

**Comment by hamchapman** [comment]
Follow up if there's a way to reproduce this. Closing for now

**Comment by marklochrie50265** [comment]
Im also having this issue, any update on this?

**Comment by hamchapman** [comment]
@marklochrie50265 do you have a sample project I can take a look at that's got this problem? I don't have the problem locally and I'm using Xcode 7.3 and the latest version of the Swift library

**Comment by marklochrie50265** [comment]
Seems this issue has gone think i was running an older version and somewhere it was being overwritten.

**Comment by Yize-Jiang** [comment]
having the same problem, using Xcode 11 and Swift 4, iOS 13.2 project on a device iPhone 10, iOS 13.3. Is it still possible to use it?
`dyld: Library not loaded: @rpath/PusherSwift.framework/PusherSwift`
`...Frameworks/PusherSwift.framework/PusherSwift: code signature invalid for.....`
`...Frameworks/PusherSwift.framework/PusherSwift: stat() failed with errno=25...`
`...Frameworks/PusherSwift.framework/PusherSwift: stat() failed with errno=1...`
