### ISSUE TITLE
Binded to events but only "pusher:subscription_succeeded" is triggered

### ISSUE THREAD

**Issue by kcw-grunt** [pusher/pusher-websocket-swift#201]
### Steps to reproduce
Followed to install basic steps per the iOS Swift (PusherSwift 6.0) cocoapod
Able to init the pusher client, subscribe to the presence channel
, bind to custom events.

### Expected behavior
Waited to read log to see if events would appear. 

What did you expect to happen?
Expected custom events e.g; "call_accepted" to appear

### Actual behavior
Only received "pusher_internal:subscription_succeeded"

 
 
for eventName in pusherEventNames {
            DoDLog("PUSHER: Binding to event: \(eventName)")
            _ = pusherPresenceChannel?.bind(eventName: eventName, callback: { data in
           if let dict = data as? [String: Any], let name = dict["channel"] as? String, let eventName = dict["event"] as? String {
                                        let timestamp = Date().timeIntervalSince1970
                    print(data.debugDescription)
                                        self.handlePusherEvent(eventDictionary: ["channel":name, "event_name":eventName, "notifications_timestamp":timestamp])
                                    } else {
                                        self.handlePusherEvent(eventDictionary: ["event_name":"EVENT TRIGGERED BUT NOT PARSED"])
                                    }
            })
        }

**Comment by TomKemp** [comment]
I'm going to close this issue, but please let me know if you're still having problems. Sorry that you didn't receive a reply.
