### ISSUE TITLE
Socket is always reconnected after I received push notification.

### ISSUE THREAD

**Issue by yukitoto** [pusher/pusher-websocket-swift#202]
### Steps to reproduce
1. Disconnect connection of pusher
2. Change application status to background status.
3. Get push notification.

The change log of status are ...
1. disconnected
2. disconncted
3. connected

### Expected behavior
I want to keep disconnected while the app in background.

### Actual behavior
The connection is always reconnected after push notification.

...

The app performance and network usage is affected this issue.
I think the priority is very high.

**Comment by yukitoto** [comment]
@hamchapman Do you have any idea for this issue?

**Comment by yukitoto** [comment]
When I change `autoReconnect` to false, this issue is not reproduced.
The work-around I take is implement auto reconnect logic by myself.

**Comment by danielrbrowne** [comment]
@yukitoto Apologies that you didn't get a timely reply to this issue... What version of the SDK are you using? Do you still see the same behaviour on our latest release, v9.0.0?

**Comment by danielrbrowne** [comment]
Since the latest v9.1.0 release contains reconnection functionality improvements, and since there has been no response, I'll close this issue for now. If it's still a problem, please feel free to reopen this issue.
