### ISSUE TITLE
Swift 5

### ISSUE THREAD

**Issue by kiritokatklian** [pusher/pusher-websocket-swift#213]
### Steps to reproduce

What must I do to reproduce the bug?
Compile the project in Xcode 10.2 with Swift 5

### Expected behavior

What did you expect to happen?
Compile without errors

**Comment by TomKemp** [comment]
Thanks for opening an issue. I've been able to replicate the issue and I'm working on a fix.

**Comment by TomKemp** [comment]
Just to make sure I am replicating the same problem, can you confirm how you are compiling the library? Are you using CocoaPods? What errors do you get?

**Comment by kiritokatklian** [comment]
@TomKemp Sorry for the late reply. Yes I'm using the CocoaPods version and manually changed the Swift version of PusherSwift to Swift 5. I got the following error in `PusherConnection.swift`, `PusherChannel.swift` and `PusherSwift.swift`:

`'let' properties are implicitly 'final'; use 'public' instead of 'open'`

**Comment by TomKemp** [comment]
Thanks for clarifying. I released a new version of the library yesterday that fixes this issue. Let me know if you have any further problems.

**Comment by kiritokatklian** [comment]
Awesome, everything is working fine on the latest version.
