### ISSUE TITLE
Receiving Data events multiple times IOS

### ISSUE THREAD

**Issue by sijjeel** [pusher/pusher-websocket-swift#217]
I have a Auth Channel to authorize the user, once this channel authorises i have to call different events to fetch data. but each event is gets called multiple times which made my login too slow. 
Why pusher is seding me events multiple times and what could be the workaround?
Any help will be highly appreciated.

Regards

**Comment by TomKemp** [comment]
Hi @sijjeel,

I think Pusher Support may be better able to assist with that question. If you're still having problems, you can create a support ticket here: https://support.pusher.com/hc/en-us/requests/new
