### ISSUE TITLE
Swift 5 Compatibility

### ISSUE THREAD

**Issue by thirdmanrecords** [pusher/pusher-websocket-swift#218]
### Steps to reproduce

What must I do to reproduce the bug?

### Expected behavior

What did you expect to happen?

### Actual behavior

What actually happened? Submit stack traces or anything that you think would help.

### Any improvements you suggest

Here is my Podfile dependencies:
  - PusherSwift (7.0.0):
    - CryptoSwift (~> 0.9)
    - ReachabilitySwift (= 4.3.0)
    - Starscream (~> 3.0.5)

I am receiving the error: Command CompileSwift failed with a non zero exit code when attempting to compile for Swift 5. Is PusherSwift 7.0 Swift5 compatible? Also, It appears that the Starscream version being pulled in might not be 3.1 (which brought in Swift 5 compatibility).

**Comment by TomKemp** [comment]
PusherSwift 7.0.0 can be compiled using the Swift 5 complier. What is the error that you get?

**Comment by thirdmanrecords** [comment]
I am getting a command CompileSwift failed with a non-zero exit code on Starscream. v3.1.0 of Starscream introduced Swift5 compatibility. Is PusherSwift loading this version? Thanks!

**Comment by thirdmanrecords** [comment]
Looks like I required a pod deintegrate and all is compiling now. Thanks
