### ISSUE TITLE
Subscribe/unsubscribe on non-main thread can cause crash, because internal dictionary is not thread-safe

### ISSUE THREAD

**Issue by dtirer** [pusher/pusher-websocket-swift#219]
### Steps to reproduce

I'm using version 7.0.0

Unfortunately uncertain of the steps to reproduce, but i have a large number of the following crashes

### Actual behavior

<img width="1119" alt="Screen Shot 2019-05-30 at 2 48 05 PM" src="https://user-images.githubusercontent.com/639812/58656346-2074e280-82ea-11e9-876b-72576a4e5708.png">

**Comment by TomKemp** [comment]
I think I've been able to replicate this issue.

I was able to replicate it by rapidly subscribing and unsubscribing from channels on a thread that isn't the main thread. The stack trace for the exception in your screenshot shows a message being processed from the websocket, which runs on the main thread and involves reading the message's channel from a Dictionary in `PusherChannels.find`. If you call a method that modifies that Dictionary (e.g. `subscribe` or `unsubscribe`) concurrently on a different thread then you can get the above exception. 

I've started working on a fix for this. I'll let you know when I merge it.

**Comment by dtirer** [comment]
@TomKemp i just wanted to follow up on this issue.
