### ISSUE TITLE
Pusher swift package is broken

### ISSUE THREAD

**Issue by fishercraigj** [pusher/pusher-websocket-swift#230]
### Steps to reproduce

I'm using Xcode 11 GM2

### Expected behavior

I'd expect to be able to use the swift package manager  =)

### Actual behavior

![Screen Shot 2019-09-23 at 4 38 02 PM](https://user-images.githubusercontent.com/1421161/65470573-a9c39e00-de20-11e9-8f7b-518850a7783f.png)

...

**Comment by joshbillions** [comment]
Same issue here with Xcode 11 11A420a

**Comment by TomKemp** [comment]
Hi, thanks for reporting this. There is a PR (#224) that should resolve this which I am hoping to get merged this week.

**Comment by TomKemp** [comment]
I've just released version `7.2.0` with Swift Package Manager support. Let me know if you have any problems using that.
