### ISSUE TITLE
Fix build warnings for CryptoSwift and ReachabilitySwift

### ISSUE THREAD

**Issue by marcetcheverry** [pusher/pusher-websocket-swift#238]
Both `CryptoSwift` and `ReachabilitySwift` have about a dozen warnings when building with a modern toolchain (Xcode 11.2.1)

Is there a possibility of either updating the version references to these libraries, or forking them for Pusher if they are abandoned and quieting the warnings?

```
▸ ⚠️  /Pods/CryptoSwift/Sources/CryptoSwift/Foundation/Data+Extension.swift:22:13: variable 'bytesArray' was never mutated; consider changing to 'let' constant
▸         var bytesArray = bytes
▸         ~~~ ^

▸ ⚠️  Pods/ReachabilitySwift/Sources/Reachability.swift:202:6: unexpected version number in 'available' attribute for non-specific platform '*'
▸     @available(*, deprecated: 4.0, message: "Please use `connection == .wifi`")
▸      ^                      ~~~~~
```

**Comment by marcetcheverry** [comment]
For `CryptoSwift`, bumping to at least version`1.1.0`would solve those warnings:

https://github.com/krzyzanowskim/CryptoSwift/commit/50d1c03bc3420eb818c0bdfcbf1c203f174bad3e#diff-388c07370a77ff0e7cc2a08c1d407026

**Comment by marcetcheverry** [comment]
For `ReachabilitySwift`, bumping to at least version `4.3.1` would solve its warnings:

https://github.com/ashleymills/Reachability.swift/commit/aa9d567080b2adfe0d1557db76fcf9cc8f10f1dd#diff-e39c8150657acc7d742c1ade2c09e956

**Comment by JonathanDowning** [comment]
This would be resolved by merging https://github.com/pusher/pusher-websocket-swift/pull/237

**Comment by TomKemp** [comment]
Hi @marcetcheverry. CryptoSwift has now been removed and Reachability has been updated so there shouldn't be any build warnings from those two. Unfortunately, there may be some build warnings for Starscream. I hope to bump the Starscream version to resolve that, but it will involve jumping a major version and there was an API refactor so it will be more work. 

I'm going to close this issue for now but feel free to open another one if you have any problems.
