### ISSUE TITLE
Module compiled with Swift 5.1 cannot be imported by the Swift 5.1.3 compiler

### ISSUE THREAD

**Issue by nyeineiei** [pusher/pusher-websocket-swift#244]
I've built the project in Xcode 11.1 and it's working well. After I've been updated to Xcode 11.3, I've got this issue. Please check the attached file for the issue. Hope you can provide a framework that's compatible to xcode 11.3. Thanks 
![Screenshot 2020-01-13 at 9 48 04 AM](https://user-images.githubusercontent.com/33157619/72229562-919fa680-35ea-11ea-8386-04a222fbf4dc.png)

**Comment by TomKemp** [comment]
Hi @nyeineiei. The library is compatible with Xcode 11.3 as far as I'm aware. You could try building it again. How are you importing the library?

**Comment by TomKemp** [comment]
I'm going to close this PR but let me know if you're still having issues.
