### ISSUE TITLE
Starscream crash -> sub-dependencies update highly required

### ISSUE THREAD

**Issue by soryncrash13** [pusher/pusher-websocket-swift#246]
### Steps to reproduce

What must I do to reproduce the bug?
The bug may be solved by just updating your sub-dependencies, more specific the Starscream pod.

### Expected behavior

What did you expect to happen?
I expect not to see anymore crash reports from the Starscream pod.

### Actual behavior

What actually happened? Submit stack traces or anything that you think would help.

Sample stacktrace:

0
libobjc.A.dylib
objc_msgSend + 16
1
Starscream
WebSocket.swift - Line 241
FoundationStream.write(data:) + 241
2
Starscream
<compiler-generated> - Line 4333382500
protocol witness for WSStream.write(data:) in conformance FoundationStream + 4333382500
3
Starscream
WebSocket.swift - Line 1268
closure #1 in WebSocket.dequeueWrite(_:code:writeCompletion:) + 1268
4
Starscream
<compiler-generated> - Line 4333372236
thunk for @escaping @callee_guaranteed () -> () + 4333372236
5
Foundation
__NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 24
6
Foundation
-[NSBlockOperation main] + 104
7
Foundation
__NSOPERATION_IS_INVOKING_MAIN__ + 24
8
Foundation
-[NSOperation start] + 740
9
Foundation
__NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__ + 24
10
Foundation
__NSOQSchedule_f + 184
11
libdispatch.dylib
_dispatch_block_async_invoke2 + 144
12
libdispatch.dylib
_dispatch_client_callout + 20
13
libdispatch.dylib
_dispatch_continuation_pop + 408
14
libdispatch.dylib
_dispatch_async_redirect_invoke + 596
15
libdispatch.dylib
_dispatch_root_queue_drain + 348
16
libdispatch.dylib
_dispatch_worker_thread2 + 120
17
libsystem_pthread.dylib
_pthread_wqthread + 216
18
libsystem_pthread.dylib
start_wqthread + 8

I will submit all the info if you do consider it as needed, but I'd like to try and see wether or not the crash would be solved by using the latest version of Starscream library, which I highly think would. Your current subdependency for starscream is 3.0.5 (in pusher v7.2) and the latest version for starscream is 4.0.0 as of now, 28th of February 2020.

### Any improvements you suggest

Could you nicely please release a new version of pusher in which you update just your sub-dependencies?

**Comment by cthorne91** [comment]
I am experiencing a crash specifically when running on iOS Version 9.3.6 (13G37).

I've found the line that crashes. PusherSwift.swift line 29
`let ws = WebSocket(url: URL(string: urlString)!)`

I noticed if I were to breakpoint on this line, then execute in the console.
`po WebSocket(url: URL(string: urlString)!);`
then play through the breakpoint, the app will not crash.

**Comment by cthorne91** [comment]
Also, I installed the forked version from [This comment](https://github.com/pusher/pusher-websocket-swift/issues/229#issuecomment-544904417) on this #229 issue.

It did not fix this particular issue.

**Comment by bofeizhu** [comment]
@TomKemp Any update on this issue? `Starscream 4.0` is released which adds Native WS API support and Catalyst support. Our app is blocked by PusherSwift's dependency lock to 3.0.5.

**Comment by soryncrash13** [comment]
Seems like the latest version for this library is 8.0 (the moment of my writing). Gonna close the ticket since this is what I was hoping for, an update to the sub-dependencies, more precise on Starscream. Thank you very much.
