### ISSUE TITLE
Auth For Private Channels

### ISSUE THREAD

**Issue by fbarraganef** [pusher/pusher-websocket-swift#270]
The documentation is not clear, uses examples with libPusher and I'm using PusherSwift.

I'm trying to subscribe to a private channel, for accomplish that I need to authenticate.

I getting this error: 

    Error authorizing channel : No auth field in response

I'm using this example.
authMethod: AuthMethod.authRequestBuilder(authRequestBuilder: AuthRequestBuilder()),

class AuthRequestBuilder: AuthRequestBuilderProtocol {

func requestFor(socketID: String, channelName: String) -> URLRequest? {
let urlString = RequestManager.urlPusher()
guard let url = URL(string: urlString) else { return nil }
var request = URLRequest(url: url)

request.httpMethod = "POST"
request.httpBody = "socket_id=\(socketID)&channel_name=\(channelName)".data(using: String.Encoding.utf8)

//This because the url of the auth needs some custom headers. 
let headers = RequestManager.headersPusher(parameters: self.getHeaders())
for (k, v) in headers {
  request.addValue(v, forHTTPHeaderField: k)
}
return request
}

I don't know why I'm receiving that error if my authentication is everything fine. 

¿What is the reason of this? Where is an example up to date for private channels and authentication using an endpoint in Swift.

 Thanks

**Comment by fbarraganef** [comment]
Error authorizing channel :  No auth field in response

I'm using this example. 
 authMethod: AuthMethod.authRequestBuilder(authRequestBuilder:  AuthRequestBuilder()),

class AuthRequestBuilder: AuthRequestBuilderProtocol {
  
  func requestFor(socketID: String, channelName: String) -> URLRequest? {
    let urlString = RequestManager.urlPusher()
    guard let url = URL(string: urlString) else { return nil }
    var request = URLRequest(url: url)
    
    request.httpMethod = "POST"
    request.httpBody = "socket_id=\(socketID)&channel_name=\(channelName)".data(using: String.Encoding.utf8)

    //This because the url of the auth needs some custom headers. 
    let headers = RequestManager.headersPusher(parameters: self.getHeaders())
    for (k, v) in headers {
      request.addValue(v, forHTTPHeaderField: k)
    }
    return request
  }


I don't know why I'm receiving that error

**Comment by ruddfawcett** [comment]
From my understanding, if you're planning on using `func requestFor(socketID: String, channelName: String) -> URLRequest?` from the `AuthRequestBuilderProtocol`, the response from your server needs to include an `auth` field in its body.

The error you're getting is thrown here: https://github.com/pusher/pusher-websocket-swift/blob/bcfd35112a6c5533bb118e6649783343869cd183/Sources/PusherConnection.swift#L840-L844

You might want to take a look at how you're handling Pusher authentication from the API/server you're using. [You can find more info on server-side authentication here.](https://pusher.com/docs/channels/server_api/authenticating-users#server-side-implementing-authentication-endpoints) These issues can be a bit hard to debug, so I may open a PR adding the ability to dig into the authentication response when testing.

**Comment by ruddfawcett** [comment]
Actually, I take it back — you can debug the `URLResponse` by implementing the `func failedToSubscribeToChannel(...)` [delegate method](https://github.com/pusher/pusher-websocket-swift#connection-delegate) on your Pusher connection.

**Comment by fbarraganef** [comment]
Thank you so much, how I solved my problem was creating my own implementation from the Autorizer protocol, using the method:

func fetchAuthValue(socketID: String, channelName: String, completionHandler: @escaping (PusherAuth?) -> ()) 

inside this method implement the asyncronous call to my auth service then I return to the completionHandler an object PusherAuth(auth: String) with the auth received from my services, and that's it. 

Thanks.

**Comment by danielrbrowne** [comment]
@fbarraganef I'm glad to see you found a solution - are you happy for me to close this issue, or is there any action(s) the Team could take before closing the issue?
