### ISSUE TITLE
 Authorization is not working properly

### ISSUE THREAD

**Issue by devsujith** [pusher/pusher-websocket-swift#274]
I'm using Xcode 11,SWIFT 5, "PusherSwift" version 8.0.0(cocoapods) and tried using "AuthRequestBuilderProtocol" for authenticating the Pusher connection. But it's not working out properly, I'm not even able to get any logs from the below function implementation.

   ```
class AuthRequestBuilder: AuthRequestBuilderProtocol {
    var channelPath: String
    init(path: String) {
        print("this is working")
        self.channelPath = path
    }

    func requestFor(socketID: String, channelName: String) -> URLRequest? {
        
        print("this is not even called")  

        var request = URLRequest(url: URL(string: channelPath)!)
        request.httpMethod = "POST"
    
        request.setValue("someAuthToken", forHTTPHeaderField: "x-access-token")

        request.httpBody = "socket_id=\(socketID)&channel_name=\(channelName)".data(using: String.Encoding.utf8)
        return request
    }
    }
```

I tried implementing with Objective C library ("libPusher") and everything worked properly. 

Is there any other method to implement the authorization in the SWIFT library?

**Comment by wangdu1005** [comment]
I face the same issue...why AuthRequestBuilder() can not be called in swift? Anybody can save us?

**Comment by danielrbrowne** [comment]
@devsujith @wangdu1005 Are you able to post a snippet of how you are using the `AuthRequestBuilder` object you are defining to attempt authentication?

**Comment by danielrbrowne** [comment]
For instance, [this post](https://github.com/pusher/pusher-websocket-swift/issues/150#issuecomment-333794263) on another ticket shows an example of the pattern I'd expect when using `AuthRequestBuilderProtocol`

**Comment by devsujith** [comment]
@danielrbrowne I had implemented in a similar manner to the code snippet you have shared. But the "requestFor" function was never called in the AuthRequestBuilder class. 
Also I did move on in my project by using the Objective C library "libPusher" and it seems to be working fine as of now. 

Now when I try to implement the swift library i have conflict as I have been using Starscream 4.0.3 version for WebRTC and this library requires Starscream 3.1. So I think it's better for me to retry with this library once its dependency for Starscream is updated.

**Comment by wangdu1005** [comment]
> For instance, [this post](https://github.com/pusher/pusher-websocket-swift/issues/150#issuecomment-333794263) on another ticket shows an example of the pattern I'd expect when using `AuthRequestBuilderProtocol`

Thanks for your replay, but the solution demo code that you provide is a 2017 old version with some of typo. Example: channelName which he code in channel.name...so it compile error. And return with URLRequest, but he uses NSMutableURLRequest as a return type declaration.... Therefore, the this post is not work and misleading the solution.

**Comment by wangdu1005** [comment]
> @devsujith @wangdu1005 Are you able to post a snippet of how you are using the `AuthRequestBuilder` object you are defining to attempt authentication?


#### Configuration and calling method in viewDidLoad.

```
override func viewDidLoad() {
        super.viewDidLoad()
        
        let options = PusherClientOptions(
            authMethod: AuthMethod.authRequestBuilder(authRequestBuilder: AuthRequestBuilder()),
            host: .cluster("test1")
        )

        let pusher = Pusher(key: "8583939284583hdf92ds4", options: options)
        pusher.delegate = self
        pusher.connect()
        
        // bind to all events globally
        let _ = pusher.bind(eventCallback: { (event: PusherEvent) in
            var message = "Received event: '\(event.eventName)'"

            if let channel = event.channelName {
                message += " on channel '\(channel)'"
            }
            if let userId = event.userId {
                message += " from user '\(userId)'"
            }
            if let data = event.data {
                message += " with data '\(data)'"
            }

            print(message)
        })

        // callback for member added event
        let onMemberChange = { (member: PusherPresenceChannelMember) in
            print(member)
        }
        
        // channel dynamic variable
        let chatId = 8887754
        let presenceChannel = "presence-test-chat-\(chatId)"
        
        let chan = pusher.subscribeToPresenceChannel(channelName: presenceChannel, onMemberAdded: onMemberChange, onMemberRemoved: onMemberChange)
        
        let _ = chan.bind(eventName: "testXXX", eventCallback: { (event: PusherEvent) in
            
            print("Subscribed!")
            print("I can now access myId: \(chan.myId)")
            print("And here are the channel members: \(chan.members)")

            // convert the data string to type data for decoding
            guard let json: String = event.data,
                let jsonData: Data = json.data(using: .utf8)
            else {
                print("Could not convert JSON string to data")
                return
            }

            // decode the event data as json into a DebugConsoleMessage
            let decodedMessage = try? self.decoder.decode(DebugConsoleMessage.self, from: jsonData)
            guard let message = decodedMessage else {
                print("Could not decode message")
                return
            }

            print("\(message.name) says \(message.message)")
        })


        // triggers a client event on that channel
        chan.trigger(eventName: "chat", data: ["test": "some value"])
        
    }
```

#### Outside of the TestViewController but in the same .swift file.

```
class AuthRequestBuilder: AuthRequestBuilderProtocol {
    func requestFor(socketID: String, channelName: String) -> URLRequest? {
        EGLog("It didn't call!!!AuthRequestBuilder)")
        var request = URLRequest(url: URL(string: "https://try.xxxxxpusher.com/test/chats/auth")!)
        request.httpMethod = "POST"
        let tmpHttpBody = "socket_id=\(socketID)&channel_name=\(channelName)".data(using: String.Encoding.utf8)
        request.httpBody = tmpHttpBody
        request.addValue("3urji593jfjeodfjgoe0di3h5bnfdie3jrnfiru4hrfgbdjd23953bfrrffdrgvx", forHTTPHeaderField: "Authorization")
        return request
    }
}

struct DebugConsoleMessage: Codable {
    let name: String
    let message: String
}

```

Note: I follow the PusherSwift installation guide to implement it, but not using the Objective-C lib or any other third party such as Starscream.... Can help me figure out this issue of official install guide? Thanks you so much!

**Comment by danielrbrowne** [comment]
@devsujith @wangdu1005 I think I have the solution to the issue you are both seeing - please note the following from the README:

> **Important:** You must keep a strong reference to the Pusher client. You could achieve that by making pusher a property of your app delegate, for example.

Since you define an instance of `Pusher` within the `viewDidLoad()` method that goes immediately out of scope when that method returns, the `requestFor(socketID: String, channelName: String) -> URLRequest?` method will never be called. Other than the AppDelegate property suggestion in the README note, another way you might achieve the same strong reference capture is a wrapper class around the Pusher Channels logic, something like:

swift```
import Foundation
import PusherSwift

typealias Channel = PusherChannel
typealias PresenceChannel = PusherPresenceChannel
typealias PresenceChannelMember = PusherPresenceChannelMember
typealias ChannelEvent = PusherEvent

class TestAuthRequestBuilder: AuthRequestBuilderProtocol {
    func requestFor(socketID: String, channelName: String) -> URLRequest? {
        print("HELLO FROM AUTHREQUESTBUILDER!")
        var request = URLRequest(url: URL(string: "http://localhost:9292/builder")!)
        request.httpMethod = "POST"
        request.httpBody = "socket_id=\(socketID)&channel_name=\(channelName)".data(using: String.Encoding.utf8)
        request.addValue("myToken", forHTTPHeaderField: "Authorization")
        return request
    }
}

final class ChannelsManager {

    static let shared = ChannelsManager()

    private static let kPusherClusterId = "SOME_CLUSTER_ID"
    private static let kPusherAppKey = "SOME_APP_KEY"

    private let pusher: Pusher

    init() {
        let options = PusherClientOptions(
            authMethod: .authRequestBuilder(authRequestBuilder: TestAuthRequestBuilder()),
            host: .cluster(Self.kPusherClusterId)
        )

        pusher = Pusher(
            key: Self.kPusherAppKey,
            options: options
        )

        pusher.delegate = self

        pusher.connect()
    }

    // MARK: - Public methods

    func subscribeToPresenceChannel(_ channelName: String, membersChangedCallback: @escaping () -> Void) -> PresenceChannel {
        return pusher.subscribeToPresenceChannel(channelName: channelName,
                                                 onMemberAdded: { addedChannelMember in
                                                    membersChangedCallback()
        }) { removeChannelMember in
            membersChangedCallback()
        }
    }

    func subscribe(to eventName: String,
                   on channelName: String,
                   eventCallback: @escaping (ChannelEvent) -> Void) -> String {

        // subscribe to channel
        let channel = subscribe(to: channelName)

        // bind a callback to handle an event
        return bind(eventName: eventName,
                    on: channel,
                    callback: eventCallback)
    }

    func subscribe(to channelName: String) -> Channel {
        return pusher.subscribe(channelName)
    }

    func unsubscribe(from channelName: String) {
        pusher.unsubscribe(channelName)
    }

    func bind(eventName: String,
              on channel: Channel,
              callback: @escaping (ChannelEvent) -> Void) -> String {
        return channel.bind(eventName: eventName, eventCallback: callback)
    }

    func unbindEventCallback(withId callbackId: String) {
        pusher.unbind(callbackId: callbackId)
    }
}
```
That's not a complete implementation of such a wrapper class, but the important point is it holds the `Pusher` object as a private property, and has a `shared` singleton which will persist for the lifetime of the app execution. Please let me know if either of these approaches solve your issues with the `AuthRequestBuilderProtocol` auth method.

**Comment by wangdu1005** [comment]
@danielrbrowne Thanks you so much!!!! you point out my typo, and misunderstanding of Docs. I declare a strong reference in test class, but use local variable in function viewDidLoad.... The problem solved after I assigned the Pusher object instance into class variable.

The wrapper class that you provides is a very beautiful works. Does any other official demo or blogger tutorial information can teach us how to have more "completely" using singleton wrapper class of pusher manager?

**Comment by danielrbrowne** [comment]
@wangdu1005 I'm glad that has resolved your issue. Are you happy for me to close this issue?

In terms of tutorials or example code, this is something that we always look to improve - there's nothing specific at the moment on a wrapper class for the Pusher library, but the wrapper pattern is a common way of abstracting away specific third libraries in your codebase to make refactors easier if there are breaking API changes in the future, so you only need to change the calls in a single place in your code.

**Comment by devsujith** [comment]
@danielrbrowne will try this out once the library updates the Starscream dependency to 4.0.3 or above. Thanks for the support.
