### ISSUE TITLE
Websocket is disconnected. Error: The operation couldn’t be completed. (PusherSwift.WSError error 1.)

### ISSUE THREAD

**Issue by sujitkaulavkar123** [pusher/pusher-websocket-swift#276]
Hello Team, 

 I am using Pusher for all iOS, Android and Web. It is working extremely well. But for sometime it fails at a time in both iOS and Android. 
When I checked the iOS log I got the error as 
`Websocket is disconnected. Error: The operation couldn’t be completed. (PusherSwift.WSError error 1.)`

  For iOS, we are using library pod version as 5.1.1 

  Any help is really appropriate.

**Comment by danielrbrowne** [comment]
@sujitkaulavkar123 Are you able to give any more specific reproduction steps for this crash? Do you still see the crash if you use the latest (i.e. v8.0.0) of the PusherSwift library?

**Comment by danielrbrowne** [comment]
v9.0.0 has recently been released, complete with a fully-native WebSocket client internal to the SDK. I'd be interested to know if you still see this issue using this version?

**Comment by danielrbrowne** [comment]
Since the latest v9.1.0 release contains reconnection functionality improvements, and since there has been no response, I'll close this issue for now. If it's still a problem, please feel free to reopen this issue.
