### ISSUE TITLE
Websocket disconnected

### ISSUE THREAD

**Issue by rjong** [pusher/pusher-websocket-swift#28]
Hi,
I want to subscribe on a channel to fire a function when the event is send.

In the viewDidLoad, I have
```
let pusher = Pusher(key: Constraints.data.PUSHER_KEY)
pusher.connect()
let chan = pusher.subscribe("bestelling")      
chan.bind("nieuwe_bestelling", callback: { (data: AnyObject?) -> Void in
    if let data = data as? Dictionary<String, AnyObject> {
    if let testVal = data["test"] as? String {
                    print(testVal)
       }
    }
    self.dataOphalen()
 })
```

But after 2 seconds I'll get: Websocket is disconnected: connection closed by server

What to do?

**Comment by hamchapman** [comment]
That sounds pretty weird! 

If you just have 

```
let pusher = Pusher(key: Constraints.data.PUSHER_KEY)
pusher.connect()
```

does the same thing happen?

**Comment by rjong** [comment]
@hamchapman Yup. Get the same message.

**Comment by hamchapman** [comment]
Is your `PUSHER_KEY` value definitely being set and retrieved properly such that the key you give to the `Pusher` initialiser is a valid key? 

It seems like a strange error to be getting! 

You could try using libPusher (https://github.com/lukeredpath/libPusher) and call into it using Swift and see if you get the same problem?

**Comment by rjong** [comment]
Ow wow, I'm so stupid!
I mixed up the key and secret.

Sorry and thanks.
