### ISSUE TITLE
Crash: dyld: Symbol not found: _OBJC_CLASS_$_Reachability

### ISSUE THREAD

**Issue by failynsedik** [pusher/pusher-websocket-swift#288]
### Steps to reproduce

I just installed the pod on an existing app and it crashed. However, when I tried it on a new Xcode project, there was no crash and it was working perfectly.

What could help pinpoint the issue is that I previously already have the [Reachability.swift](https://github.com/ashleymills/Reachability.swift/blob/master/Sources/Reachability.swift) file copied directly on my existing app. However, when I deleted it, the crash is still there. I also have [Reachability](https://github.com/tonymillion/Reachability) library by _Tony Million_ through another pod, but I have no idea which one.

### Expected behavior

No crash on app launch.

### Actual behavior

App crashed on launch with the following crash logs.

```
dyld: Symbol not found: _OBJC_CLASS_$_Reachability
  Referenced from: /Users/abc/Library/Developer/CoreSimulator/Devices/387D652C-CB80-4739-88B1-DD04ACAFA8D6/data/Containers/Bundle/Application/749E2EB8-AD62-438E-8EE8-7AAF5E8C3028/LalaFood-User.app/Frameworks/ChatSDK.framework/ChatSDK
  Expected in: /Users/abc/Library/Developer/CoreSimulator/Devices/387D652C-CB80-4739-88B1-DD04ACAFA8D6/data/Containers/Bundle/Application/749E2EB8-AD62-438E-8EE8-7AAF5E8C3028/LalaFood-User.app/Frameworks/Reachability.framework/Reachability
 in /Users/abc/Library/Developer/CoreSimulator/Devices/387D652C-CB80-4739-88B1-DD04ACAFA8D6/data/Containers/Bundle/Application/749E2EB8-AD62-438E-8EE8-7AAF5E8C3028/LalaFood-User.app/Frameworks/ChatSDK.framework/ChatSDK
```

Hoping someone could help. Thank you.

**Comment by failynsedik** [comment]
For the time being, in order to proceed with my task at work, I just manually copied the files I need from `PusherSwift`, instead of doing a `pod install`.

**Comment by danielrbrowne** [comment]
Reachability is now no longer a dependency of this SDK, as of the v9.1.0 release. Upgrading to the latest version should resolve this issue.
