### ISSUE TITLE
TVOS support for PusherSwiftWithEncryption

### ISSUE THREAD

**Issue by denisblondeau** [pusher/pusher-websocket-swift#298]
Is there any timeline regarding being able to use PusherSwiftWithEncryption with a TVOS app? My understanding is that the problem lies with Sodium not supporting TVOS.

BTW - PusherSwift integration with my TVOS app works really well.

Thank you.

**Comment by danielrbrowne** [comment]
@denisblondeau You are correct, currently [swift-sodium](https://github.com/jedisct1/swift-sodium) does not support tvOS.

I have raised [this issue](https://github.com/jedisct1/libsodium/issues/1004) to investigate whether this is pending work, but it may be a technical limitation of tvOS itself. I will keep this issue updated with anything I found out.

**Comment by denisblondeau** [comment]
Thank you for your reply, @danielrbrowne; much appreciated.

**Comment by danielrbrowne** [comment]
Re-opened because there are no technical limitations in theory (as confirmed with swift-sodium's maintainer).
