### ISSUE TITLE
Pusher shows only connecting state

### ISSUE THREAD

**Issue by AhmedAbdeen11** [pusher/pusher-websocket-swift#305]
I just implemented pusher for first time on IOS. I implemented it before on android and it works perfectly. But on IOS it doesn't connect. I receive only one message in delegate function changedConnectionState. Which return old: disconnected, new: connecting. Then nothing else. On debug console no connection is shown or anything. I looked everywhere but not sure what is going on. I implemented this quick guide: https://pusher.com/docs/channels/getting_started/ios

My code in swift 5, ios 13.2, Xcode 11.3.1:

       let options = PusherClientOptions(
          host: .cluster("eu")
        )

        let pusher = Pusher(key: "App_Key", options: options)
        
        pusher.connection.delegate = self
        
        pusher.connect()
        
        let myChannel = pusher.subscribe("chat.16")
        
        let _ = myChannel.bind(eventName: "new-message", callback: { (data: Any?) -> Void in
          print(data)
        })

**Comment by ben-pusher** [comment]
Hi, 
This looks like one our Support team are best placed to help you with - can you raise a ticket via https://support.pusher.com/hc/en-us?

**Comment by MarioPcol** [comment]
@AhmedAbdeen11  What was your solution? I'm facing the same issue
