### ISSUE TITLE
Build fail on release for ios when it's compiling Pusher.

### ISSUE THREAD

**Issue by isaacadariku** [pusher/pusher-websocket-swift#309]
### Steps to reproduce
Build your app using "flutter build ios"
go to Xcode to prepare ipa for store
Click Product > Archive
when it get to compiling Pusher pod, build failed

### Expected behavior

Building Failed and error points to Pusher

### Actual behavior

Undefined symbols for architecture armv7:
  "static Reachability.Reachability.Connection.__derived_enum_equals(Reachability.Reachability.Connection, Reachability.Reachability.Connection) -> Swift.Bool", referenced from:
      function signature specialization <Arg[0] = Dead> of PusherSwift.PusherConnection.websocketDidDisconnect(socket: Starscream.WebSocketClient, error: Swift.Error?) -> () in PusherWebsocketDelegate.o
  "Reachability.Reachability.startNotifier() throws -> ()", referenced from:
      PusherSwift.PusherConnection.connect() -> () in PusherConnection.o
  "type metadata for Reachability.Reachability", referenced from:
      closure #1 () -> Reachability.Reachability? in PusherSwift.PusherConnection.reachability.getter : Reachability.Reachability? in PusherConnection.o
      function signature specialization <Arg[0] = Dead> of PusherSwift.PusherConnection.websocketDidDisconnect(socket: Starscream.WebSocketClient, error: Swift.Error?) -> () in PusherWebsocketDelegate.o
  "Reachability.Reachability.stopNotifier() -> ()", referenced from:
      PusherSwift.PusherConnection.disconnect() -> () in PusherConnection.o
  "type metadata accessor for Reachability.Reachability", referenced from:
      closure #1 () -> Reachability.Reachability? in PusherSwift.PusherConnection.reachability.getter : Reachability.Reachability? in PusherConnection.o
  "Reachability.Reachability.connection.getter : Reachability.Reachability.Connection", referenced from:
      function signature specialization <Arg[0] = Dead> of PusherSwift.PusherConnection.websocketDidDisconnect(socket: Starscream.WebSocketClient, error: Swift.Error?) -> () in PusherWebsocketDelegate.o
  "Reachability.Reachability.__allocating_init(queueQoS: Dispatch.DispatchQoS, targetQueue: __C.OS_dispatch_queue?) -> Reachability.Reachability?", referenced from:
      closure #1 () -> Reachability.Reachability? in PusherSwift.PusherConnection.reachability.getter : Reachability.Reachability? in PusherConnection.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
See below for more screenshots

![Screenshot 2020-11-09 at 07 30 14](https://user-images.githubusercontent.com/46024202/98507882-c4441b00-225e-11eb-87d6-da0811384645.png)
![Screenshot 2020-11-09 at 07 30 35](https://user-images.githubusercontent.com/46024202/98507886-c908cf00-225e-11eb-8c48-f1a0f0575860.png)

### Any improvements you suggest
Plugin should be updated to fit the new swift 5
...

**Comment by danielrbrowne** [comment]
@isaacadariku Can I ask which version of the Swift Channels SDK you are using? For reference, the latest version is 9.0.0

**Comment by isaacadariku** [comment]
@danielrbrowne please how can I check it? I have no idea about swift channel..

Cos it complies well on Andriod

**Comment by danielrbrowne** [comment]
How are you integrating this SDK? Is it via Cocoapods, Carthage, Swift Package Manager, or a direct download?

**Comment by isaacadariku** [comment]
Okay

I use cocoapods, the normal put the  pubspec.yaml, while building for ios, it install all pods. That is it. 

My Xcode version is 11.3.0.1

**Comment by danielrbrowne** [comment]
It looks like Flutter has possibly not downloaded the Reachability framework. (This is a dependency of the PusherSwift SDK). I am not very familiar with Flutter, but can you ensure that it is downloading all the dependencies when installing PusherSwift?

**Comment by danielrbrowne** [comment]
I'll close this issue for now since there's been no reply for a week - if you're still having this issue, please feel free to re-open it or contact Pusher Customer Support for further help.
