### ISSUE TITLE
Many pusher errors with messages lost

### ISSUE THREAD

**Issue by benjamincombes** [pusher/pusher-websocket-swift#311]
### Steps to reproduce

1. Connect to Pusher on an app with medium-quality connexion (about 50Mbps in Wifi, not even a really bad one like 3G on a train)

### Expected behavior

In most cases, connexion should be OK, and all messages should be received

### Actual behavior

Many errors are showing for many of our users. So the connection is stopped, then restored, but meanwhile the user didn't receive some messages. We are 5 employees working remotely, on these 5, 3 of them are having problems with pusher connexion very regularly (messages are lost, from 1% to about 15% of the time). It was the case with users from https://www.usertesting.com/ too, where 2 users out of 5 had the problem.
I have been using pusher websocket JS for a few years on a large scale project (millions of users monthly) without any of these problems, including within a webview included in an iOS app. On this new project using pusher-websocket-swift, the error rate looks really high to me. The enclosed screenshot is for members of our team, 5 people only.
<img width="1792" alt="Screenshot 2020-11-10 at 17 40 02" src="https://user-images.githubusercontent.com/138637/98968682-45750980-250e-11eb-9880-78b4826b2b87.png">
To be noted that users with really nice connexion do never get these errors (we had to work remotely to detect it). But for other ones, the app is nearly impossible to use.

### Any improvements you suggest

Check if this is really a normal behavior due to bad conditions, or if it's due to a bug in the library. But looking at how often it happens, I would be surprised that it's only due to a bad network. I wouldn't be surprised that it happens, but not so often. Let me know if I can give any additional information, thanks.

**Comment by danielrbrowne** [comment]
Which version of the SDK are you seeing this behaviour with?

**Comment by benjamincombes** [comment]
Hi @danielrbrowne, I had this problem with 8.0.0 and 9.0.0

**Comment by benjamincombes** [comment]
Hi @danielrbrowne, any news on this? We added some server-side retries to make the problem less visible, but it would be great if you could investigate the problem, let me know if I can be of any help.

**Comment by danielrbrowne** [comment]
I am actively investigating both this issue and #310. Given that the reconnection issue is a regression I am primarily focussing on that, since you mentioned that the error logging in this issue also occurs on v8.0.0 of the SDK.

I will update both issues once a fix is available.

**Comment by benjamincombes** [comment]
Thanks a lot, don't hesitate if you need more details/logs/code!
