### ISSUE TITLE
Cannot pod install to get v9.0

### ISSUE THREAD

**Issue by kyweng** [pusher/pusher-websocket-swift#325]
I'm getting this error when pod install / pod update

[!] CocoaPods could not find compatible versions for pod "PusherSwift":
  In Podfile:
    PusherSwift (~> 9.0)

Specs satisfying the `PusherSwift (~> 9.0)` dependency were found, but they required a higher minimum deployment target.

**Comment by ben-pusher** [comment]
The SDK minimum deployment targets are now iOS 13.0, macOS 10.15 and tvOS 13.0. You will need to ensure your app targets these versions as a minimum.

**Comment by danielrbrowne** [comment]
@kyweng Alternatively, if you cannot for whatever reason update your app to target these higher minimum deployment target versions - you can continue to use v8.0.0 of the SDK instead.

**Comment by danielrbrowne** [comment]
If you still have questions - please feel free to contact us at support@pusher.com
