### ISSUE TITLE
How to set Cluster and Host at the same PusherClientOptions

### ISSUE THREAD

**Issue by kyweng** [pusher/pusher-websocket-swift#326]
May I know how can I set the cluster and host at the same PusherClientOptions?

This is my code:
let pusherClientOptions = PusherClientOptions(
                     host: .host("abc.com"),
                     host: .cluster("abc")
                 )

**Comment by danielrbrowne** [comment]
The `PusherHost` passed into the `PusherClientOptions` initialiser is an `enum`, and therefore can be one of two case values:
- `.host("someWebSocketHost.com")` - This would be a custom webserver which sends messages according to the Pusher Channels Protocol.
- `.cluster("eu") - This would be the cluster name that refers to the cluster you chose when you set up your Pusher Channels app on the [Pusher Dashboard](https://dashboard.pusher.com/).

So, it is not possible to set the host to a custom host and a cluster at the same time.

**Comment by danielrbrowne** [comment]
If you still have questions - please feel free to contact us at support@pusher.com
