### ISSUE TITLE
Can't connect to custom server using 9.0.0 or above

### ISSUE THREAD

**Issue by nicoreese** [pusher/pusher-websocket-swift#328]
### Steps to reproduce

The basic setup I have is this. I use my own server using the Pusher protocol. When the connection changes from disconnected to connecting, an error occurs.

```
let options = PusherClientOptions(
           host: .host("DOMAIN"),
           port: 6001
       )
       
       pusher = Pusher(key: "XXXXX", options: options)
       pusher.connection.delegate = self
       pusher.connect()
```

### Expected behavior

Pusher should connect to my server without errors.

### Actual behavior

In the current version 9.1.1 I receive the following error when running the code above:
`[PUSHER DEBUG] Websocket received error. Error: POSIXErrorCode: Software caused connection abort
`
I tried version 9.0.0 as well where the same issue occurs with a different error message:
`[PUSHER DEBUG] Websocket received error. Error (code: 0): The operation couldn’t be completed. (Network.NWError error 0.)
`
And lastly, I tried the same piece of code in version 8. There it works just fine and the connection is established without issues.

I also use the same server in a ReactJS environment where the connection works fine as well. Finally, I can connect to my server in this Webecho Test http://websocket.org/echo.html, so I can rule out that the server is the issue. Using the SDK with the Pusher service itself works fine in any version I tested, it's just an issue with custom servers.

**Comment by danielrbrowne** [comment]
Thanks for opening a new issue to report this. The Pusher team are winding down for the holidays now, but I will look into this in detail when I am back in January.

In the meantime, if you are able to us v8.0.0 instead without issue with your custom server, please continue to do so.

**Comment by danielrbrowne** [comment]
@nicoreese Are you able to post logs from your server (or examine yourself if you cannot post them) that might contain some error logging or more insight into how your custom server is handling the connection attempt?

Also, can I confirm that your custom server is respecting the [Pusher Channels Protocol closure codes](https://pusher.com/docs/channels/library_auth_reference/pusher-websockets-protocol#connection-closure) correctly?

**Comment by TheRakiburKhan** [comment]
Has anyone found any solution other than downgrading to version 8? I am using version 10.1.2 and the problem still exists with the same error,
``
[PUSHER DEBUG] Websocket received error. Error: POSIXErrorCode(rawValue: 53): Software caused connection abort
``

**Comment by IH0kN3m** [comment]
I cannot believe the issue still persists in 10.1.5, also had to downgrade to version 8 and it works fine now
