### ISSUE TITLE
Subscribe to multiple channels

### ISSUE THREAD

**Issue by ashutoshjha1409** [pusher/pusher-websocket-swift#33]
Hi
I'm trying to subscribe to multiple channels to the same pusher object. But your documentation doesn't suggest much. 
What I'm trying to do is something like this:

```
// Class properties
let pusher = Pusher(key: Config.Constant.pusherAppKey)
var myChannel:PusherChannel?

override func viewDidAppear(animated: Bool) {
    // PUSHER CONNECT?SUBSCRIBE
    self.pusher.connect()
    self.myChannel = self.pusher.subscribe(["temp_testing_channel", "all_test_channels"])
}
```

But there is an error:
`Contextual type 'String' cannot be used with array literal`

**Comment by hamchapman** [comment]
This isn't currently possible but shouldn't be hard to add. 

If you want to make a PR for it, go for it! :+1: 

Otherwise I (or someone else) will get to this soon enough

**Comment by xeo-it** [comment]
This would be really good actually, having multiple pusher instances for different channels it's not very handy.

**Comment by hamchapman** [comment]
To be able to bind to events on the individual channels that are subscribed to you obviously still need to be able to get the relevant channel object. This is fine if you're happy to use `pusher.connection.channels.channels.find("CHANNEL_NAME")`, but that doesn't seem great. 

Is your use case that you just want to be subscribed to a load of channels and then bind to events at the global level? 

Or would it be better to return an array of channels?

**Comment by hamchapman** [comment]
Closing as stale - this is something that I've not seen requested by anyone else so unless there's more interest this won't be added 👍
