### ISSUE TITLE
Carthage xcframework support for v8.x

### ISSUE THREAD

**Issue by r-plus** [pusher/pusher-websocket-swift#341]
### Steps to reproduce

not a bug. feature request.

### Expected behavior

Pusher v8.x for older os version supporting project can build xcframework via carthage v0.37.0.

### Actual behavior

- Pusher itself and Sodium dependency framework_search_path is not compatible for it.

Do you have any plan to support it by releasing v8.0.1?

**Comment by ben-pusher** [comment]
Could you share the OS version and Xcode version you are using, along with the full error message being encountered and at what point you encounter the error?

**Comment by danielrbrowne** [comment]
@r-plus We are only committing to critical bug fixes for future v8.x releases. [See here](https://blog.pusher.com/channels-ios-swift-v9-0-0-refreshing-the-sdk-with-a-flexible-native-websocket-client/). Specifically:

> Critical bug fixes will be applied to both the v8.x and v9.x releases. These bug fixes will be available as part of v8.x releases until October 1st 2021.

**Comment by r-plus** [comment]
ok, sure.
