### ISSUE TITLE
Problems connecting with versions 9.0+

### ISSUE THREAD

**Issue by spasbilyarski** [pusher/pusher-websocket-swift#352]
### Steps to reproduce

1. Setup a socket connection with a host and not a cluster:
```
        let options = PusherClientOptions(autoReconnect: true, host: PusherHost.host(Configuration.socketsBaseURL.absoluteString), useTLS: true)
        pusher = Pusher(key: Configuration.socketsAPIKey, options: options)
        pusher?.connect()
```

2. Observe debug logs:
```
[] nw_protocol_copy_ws_definition_block_invoke [C2.1:1] nw_ws_validate_server_response
[PUSHER DEBUG] Websocket received error. Error: POSIXErrorCode: Software caused connection abort
```

### Expected behavior

Connect to the server and proceed with channel subscription.

### Actual behavior

No connection is made, observed errors in console.

### Notes

I was not able to make this work with versions 9.x but the same code base works with version 8.0.

**Comment by benw-pusher** [comment]
Hi, could you let us know what you are setting your host to? Does it work if you set a cluster instead of setting a host directly?

**Comment by spasbilyarski** [comment]
Hi, needed to ask our backend because I just knew that we were using our own server and nothing more. Turns out we are using Laravel Websockets by Beyond Code that in their words should be "drop-in Pusher API replacement". Now that I have this information it is most likely a compatibility issue with the versions. Can you confirm? 
PS: I am ok with you closing this issue.

**Comment by benw-pusher** [comment]
I do believe this is a compatibility issue. It seems other people have encountered the same issue when using Laravel Websockets and have reverted to using v8.
Are you able to use v8 of the library for your project?

**Comment by spasbilyarski** [comment]
@benw-pusher Yes there are no problems when using v8, the issue I am seeing is only applicable to v9.0 and up

**Comment by benw-pusher** [comment]
Thanks. We replaced the underlying package that initiates the connection request in v9 so this will be the cause of the issue - however as this works well with our own service our advice would be to continue to use v8 as we can't commit to supporting custom websocket server connections.
