### ISSUE TITLE
Deliver events on background thread

### ISSUE THREAD

**Issue by nolanamy** [pusher/pusher-websocket-swift#353]
### Steps to reproduce

Subscribe to a Pusher channel and bind a callback to an event. Then, receive that event.

### Expected behavior

Callbacks are called on a background thread, as they are in https://github.com/pusher/pusher-websocket-java (thread name: `"pusher-java-client eventQueue"`)

### Actual behavior

Callbacks are called on the main thread: https://github.com/pusher/pusher-websocket-swift/blob/ca6130e552b02865472920b9ff73ee98a890fe1f/Sources/Services/PusherConnection.swift#L961

**Comment by danielrbrowne** [comment]
@nolanamy Thanks for opening the issue to identify this difference between the Swift and Java SDKs.

I know from past discussions from before I joined Pusher, there's been some hairy thread-safety issues during developing this SDK, so it may be that this use of the main queue was a workaround to some issues. I will schedule this in our roadmap and look into a thread-safe change to match the Java SDK behaviour in due course.

In the meantime, I'd be interested to hear what specific impact this is having for your use case?

**Comment by nolanamy** [comment]
@danielrbrowne sounds good.

No big impact; our event handler (common to Android and iOS via Kotlin Multiplatform) quickly dispatches to another thread in either case. Having spent more time with the Java SDK, I'd just assumed the Swift SDK was using a background thread too.

**Comment by parvez-keeptruckin** [comment]
@danielrbrowne | @nolanamy 
Is there a way to get the events in background thread from within the SDK [Pusher iOS Swift]? Looking to very high frequency of the events in my case, having events on main thread seems not a good solution. There is some processing needs to be done on the event data and if it requires UI update then we can switch to main thread else not needed.

**Comment by danielrbrowne** [comment]
@parvez-keeptruckin I am no longer a maintainer of this repo, having left the company in 2021. Perhaps @fbenevides can help?

**Comment by parvez-keeptruckin** [comment]
Thanks @danielrbrowne 
@fbenevides Any thoughts on my [comment](https://github.com/pusher/pusher-websocket-swift/issues/353#issuecomment-1971064118)
How can we make event receipts in background thread?

**Comment by parvez-keeptruckin** [comment]
@fbenevides Any update on above?
