### ISSUE TITLE
Pusher keeps on disconencting

### ISSUE THREAD

**Issue by nick70007** [pusher/pusher-websocket-swift#360]
Hello, my pusher keeps on disconnecting as soon i leave the screen, is there a way to keep pusher connected

**Comment by benw-pusher** [comment]
Is this when you leave the app entirely or just when you change screen within the app? If the latter then to solve you will need to ensure you maintain a strong reference to the Pusher object to prevent it being deallocated. 
Let me know if this helps.

**Comment by jkpatel1463** [comment]
We also face this issues.
