### ISSUE TITLE
Pusher fail to listen event changes when coming back in foreground

### ISSUE THREAD

**Issue by karenxpn** [pusher/pusher-websocket-swift#365]
I have an issue when moving the app from background to foreground, it reconnects properly but does not listen to any changes, binding is not working at all even no error is shown.
Sometimes it works okay but mostly it does not listen to events

**Comment by karenxpn** [comment]
This happens only on IOS 15, please solve this issue

**Comment by benjamin-tang-pusher** [comment]
Can you reproduce this on the simulator, or does it only happen on a physical device?

I've just updated my device to iOS 15, and I will give it a go there.

**Comment by benjamin-tang-pusher** [comment]
Can you add logging by adding the debugLog and changedConnectionState functions like this:
```
    let pusher: Pusher
    func debugLog(message: String) {
        print(message)
    }
    func changedConnectionState(from old: ConnectionState, to new: ConnectionState) {
        print("State changed from \(old.stringValue()) to \(new.stringValue())")
    }
    init() {
        let options = PusherClientOptions(...)
        pusher = Pusher(...)
        pusher.connect()
        pusher.connection.delegate = self
```
Is there anything unusual printed out when the app goes back into foreground? Could you paste it here.

**Comment by karenxpn** [comment]
it seems like everything is working now, but I haven't changed anything. et reconnects properly and doesn't throw any error 
[PUSHER DEBUG] Network connection became unviable
[PUSHER DEBUG] Websocket received error. Error: POSIXErrorCode: Socket is not connected
State changed from connected to disconnected
[PUSHER DEBUG] Websocket is disconnected but no error received Close code: Optional(1001). Reason: The websocket disconnected unexpectedly.
State changed from disconnected to reconnecting
[PUSHER DEBUG] Attempting to reconnect after waiting 0.0 seconds (attempt 1)
State changed from reconnecting to connecting
[PUSHER DEBUG] Network connection became viable
[PUSHER DEBUG] websocketDidReceiveMessage {"event":"pusher:connection_established","data":"{\"socket_id\":\"7539.22175458\",\"activity_timeout\":120}"}
[PUSHER DEBUG] Socket established with socket ID: 7539.22175458
State changed from connecting to connected

**Comment by benw-pusher** [comment]
Thanks for the update. As this is now working I'll close this out, if the issue comes back please reopen or raise a new issue.
