### ISSUE TITLE
Pusher doesn't call PusherDelegate when calls connect() with no network

### ISSUE THREAD

**Issue by sampaioroberto** [pusher/pusher-websocket-swift#366]
### Steps to reproduce

1. Implement the delegate PusherDelegate and listen to `changedConnectionState(from:, to:)` and `receivedError(error:)`
2. Call Pusher `connect()`.

### Expected behavior

If there is no internet connection when we call `connect()`, we should receive a pusher error on `receivedError(error:)`. 

### Actual behavior

The connection state changes from `disconnected` to `connecting` and it doesn't return nothing on `receivedError(error:)`. The state gets stuck in `connecting`.

### Any improvements you suggest

`PusherConnection+WebsocketDelegate` has the method `webSocketDidReceiveError(connection:, error:)`. It only logs the error. It could call `PusherDelegate` `receivedError(error:)` method.

**Comment by benjamin-tang-pusher** [comment]
receivedError(error:) is for [error codes](https://pusher.com/docs/channels/library_auth_reference/pusher-websockets-protocol/#error-codes) Pusher sends to your client. Its not for local network disconnection.

Its described in the readme https://github.com/pusher/pusher-websocket-swift#connection-delegate

Hope this clears things up.

**Comment by sampaioroberto** [comment]
Yeah, I had read that. I was just wondering that it could have an error for this network disconnection. Is there a solution for that in Pusher?
Because today this error is just logged in ```webSocketDidReceiveError(connection:, error:)```, and I receive no reply from Pusher in my code.
