### ISSUE TITLE
SWIFT: Publishing Events Without Server / Backend

### ISSUE THREAD

**Issue by interpegasus** [pusher/pusher-websocket-swift#368]
I would like to know how to publish / trigger an event to a channel directly from Swift?

The documentation mostly mentions subscriptions to channels. And a server requirement for publishing events?  

I would like to know more about the architecture on Pusher. Does pusher have servers that host the channels? Or is that a function for each individual backend? 

Thank you

**Comment by benjamin-tang-pusher** [comment]
You can use [client trigger](https://github.com/pusher/pusher-websocket-swift#triggering-events) but you will still need a server backend at least for [authentication](https://pusher.com/docs/channels/server_api/authenticating-users/).

Yes, Pusher hosts the websocket connections for the channels.

**Comment by interpegasus** [comment]
Thank you
