### ISSUE TITLE
pusher doesn't connect to server

### ISSUE THREAD

**Issue by iksandecade** [pusher/pusher-websocket-swift#372]
### Steps to reproduce

Implement Pusher same like the document
```
        let options = PusherClientOptions(host: .cluster(CLUSTER))
        let pusher = Pusher(key: API_KEY, options: options)
        
        pusher.connection.delegate = self
        
        pusher.connect()
```
### Expected behavior

Connect to server

### Actual behavior

State Connection only "State changed from disconnected to connecting" and debugLog not printed
is there something missing in my implement?

### Note
I use Xcode 13.2.1, iOS 15, Swift 5, Pusher 10.0.0

**Comment by emadsaber2024** [comment]
Issue solved with me after downgrading Pusher SDK 8.0.0. 
Problem only exists on versions after 8.0.0.
