### ISSUE TITLE
Connection automatically reconnects after intentionally calling pusher.disconnect()

### ISSUE THREAD

**Issue by quangthai206** [pusher/pusher-websocket-swift#373]
### Steps to reproduce
VERSION: "9.2.2"

1. Initialize Pusher instance: let pusher = Pusher(key: "APP_KEY")
2. Start connect to Pusher: pusher.connect()
3. Stop connect to Pusher: pusher.disconnect()

### Expected behavior

No connection to Pusher after that

### Actual behavior

After about 2 minutes, pusher automatically reconnects the connection

### Any improvements you suggest

As I investigated, the reason is because of pongResponseTimeoutTimer is triggered in PusherConnection.swift, so the connect() method is called again.

My suggestion: We can check whether to reconnect again or NOT based on `intentionalDisconnect` instance property of PusherConnection class.

<img width="619" alt="image" src="https://user-images.githubusercontent.com/42932329/150487604-dc454304-0de2-4b83-8613-281d9f9ad77e.png">

**Comment by benjamin-tang-pusher** [comment]
You're right, is reconnecting. I will get someone to take a look at your PR.
