### ISSUE TITLE
update cocoapods?

### ISSUE THREAD

**Issue by rex-remind101** [pusher/pusher-websocket-swift#378]
### Steps to reproduce

looking at github release tags the latest is 10.0.2 vs cocoapods which has 10.0.0

### Expected behavior

cocoapods also has 10.0.2 as its latest

### Actual behavior

cocoapods has 10.0.0

### Any improvements you suggest

keep cocoapods in sync with the latest release

**Comment by fbenevides** [comment]
Hi @rex-remind101, thanks for raising it.

We've just bumped the version to `10.1.0` and it's synchronised with CocoaPods.
