### ISSUE TITLE
Making channel type a enum

### ISSUE THREAD

**Issue by Austinate** [pusher/pusher-websocket-swift#38]
HI! 

While i was using PusherSwift and thought if we could improve way of handling channel identifiers. 

Main goals: 
- less error-prone channel type detection 

I thought something like this will be useful (at least to replace current calls to isPresence && isPrivate functions)
```
enum ChannelType {
    
    private static let privateChannelPrefix = "private-"
    private static let presenceChannelPrefix = "presence-"
    
    case Global
    case Private
    case Presence
    
    init(channelName: String) {
        switch channelName {
        case _ where channelName.hasPrefix(ChannelType.privateChannelPrefix):
            self = .Private
        case _ where channelName.hasPrefix(ChannelType.presenceChannelPrefix):
            self = .Presence
        default:
            self = .Global
        }
    }
    
    func idenitifer(withChannelName name: String) -> String {
        switch self {
        case .Global:
            return name
        case .Private:
            return ChannelType.privateChannelPrefix + name
        case .Presence:
            return ChannelType.presenceChannelPrefix + name
        }
    }
}
```

Probably with ability to subscribe with struct similar to this one: 
```
struct ChannelName {
    let name: String 
    let type: ChannelType

    var channelIdentifier: String {
         return type.identifier(withChannelName: name)
    }
}
```

Would be glad to hear your thoughts about this and discuss.
Thanks!

**Comment by hamchapman** [comment]
Sounds good to me! Feel free to open a PR. You might want to create it based on the split-up-and-document branch, as I think I'm going to try and get that merged soon, when I've got the documentation in place

**Comment by Austinate** [comment]
Great to hear, just didn't open PR because i saw that splitting was coming, will do soon :)
Thanks!

**Comment by hamchapman** [comment]
@Austinate the splitting has been merged along with a host of other changes for the 1.0.0 release

**Comment by hamchapman** [comment]
This has been added thanks to @Noobish1 as part of #60
