### ISSUE TITLE
Pusher state gets stuck on `disconnecting`

### ISSUE THREAD

**Issue by aheze** [pusher/pusher-websocket-swift#384]
### Steps to reproduce

This happens every so often, usually when I connect and then disconnect rapidly. Normally, from the `changedConnectionState(from old: ConnectionState, to new: ConnectionState)` function, this gets printed:

```
Connection changed: ConnectionState(rawValue: 1) -> ConnectionState(rawValue: 2) /// connected to disconnecting
Connection changed: ConnectionState(rawValue: 2) -> ConnectionState(rawValue: 3) /// disconnecting to disconnected
```

Both lines get printed right after each other. However sometimes Pusher gets stuck on this:

```
Connection changed: ConnectionState(rawValue: 1) -> ConnectionState(rawValue: 2) /// connected to disconnecting
```

Later, when I try reconnecting again, the pusher's state is still at `ConnectionState(rawValue: 2)` (.disconnecting). If I try to call `connect` nevertheless, I get the `Invalid signature: Expected HMAC SHA256` [error](https://support.pusher.com/hc/en-us/articles/4412490907921).

### Expected behavior

The `changedConnectionState` method should be called 2 times after attempting to disconnect (`connected` → `disconnecting`, then `disconnecting` → `disconnected`). The calls usually happen pretty quickly.

### Actual behavior

The second `changedConnectionState` call never happened.

**Comment by benjamin-tang-pusher** [comment]
Hi, we have a known issue 364 where disconnecting and reconnecting repeatedly cases a HMAC SHA256 error. In there I reproduced this by switching between LTE and Wifi while the app's in the background, but you've mentioned just connect and disconnecting. Are you rapidly calling the disconnect() and connect() methods?
