### ISSUE TITLE
Lack Of Good Example In Swift UI

### ISSUE THREAD

**Issue by rahat14** [pusher/pusher-websocket-swift#386]
Pusher is my go-to service for notification and other services while developing android applications. but recently i moved to IOS development with swift UI but here I see a lack of samples and examples. Please look into this problem

**Comment by benw-pusher** [comment]
Hi @rahat14. We don't supply any UI as this is beyond the scope of the realtime capabilities we provide. There are third party UI sample apps available that may meet your needs - https://iosexample.com/tag/swiftui/, however Pusher does not intend to provide any ourselves.
