### ISSUE TITLE
Watchlist and Signin method 

### ISSUE THREAD

**Issue by billypap1** [pusher/pusher-websocket-swift#402]
We use Watchlist in our JS app but we don't find any documentation about it into this library for iOS. 
There is no method "Pusher.signin()" in this library and there is authorization only per channel, not for user.
Is watchlist feature available for iOS?

**Comment by benjamin-tang-pusher** [comment]
Hi, unfortunately watchlist hasn't been implemented in our swift library yet. I will add this request to our list for our product team to prioritize however. We're keen to get it added to our mobile libraries but we can't commit to an eta yet.

**Comment by sebbu** [comment]
Hi @benjamin-tang-pusher, are there any updates on this issue?
