### ISSUE TITLE
Memory Leak with NWWebSocket

### ISSUE THREAD

**Issue by choulepoka** [pusher/pusher-websocket-swift#406]
### Steps to reproduce

- Connect to the Pusher Websocket using an instance of `Pusher`

```
let url = ...
let apiKey = ...
let key = ...
let channelName = ...
let eventName = ...
let builder = AuthRequestBuilder(authUrl: url, apiKey: apiKey)
let options = PusherClientOptions(
  authMethod: .authRequestBuilder(authRequestBuilder: builder),
  host: .cluster(cluster)
)
let pusher = Pusher(key: key, options: options)
let myChannel = pusher.subscribeToChannel(withName: channelName)
myChannel.bind(eventName: eventName, eventCallback: { event in
    // TODO handle event
})
```

- Disconnect the Pusher isntance

```
pusher.unbindAll()
pusher.unsubscribeAll()
pusher.disconnect()
pusher = nil
```

- Open the `Memory graph` in xcode, and look for surviving instance of `NWWebSocket`

### Expected behavior

No `NWWebSocket` instance are still allocated

### Actual behavior

`NWWebSocket` instances are still allocated

### Any improvements you suggest

Integrate https://github.com/pusher/NWWebSocket/pull/38

**Comment by fbenevides** [comment]
Released 10.1.3. Thanks!
