### ISSUE TITLE
Authentication to private channel

### ISSUE THREAD

**Issue by essaroj** [pusher/pusher-websocket-swift#41]
Hello sir,
        Please let me know how could i use authentication url along with headers, parameters for authenticating channel. I want to trigger event to private channel. Your documentation does not provide much information about it so please help me to get out of this.

**Comment by hamchapman** [comment]
Hi there, sorry for the slow response.

You can get a hold of the request object before the request is made and use that to set headers etc.

You'll want to specify the `authRequestCustomizer` option when you instantiate the `Pusher` client (https://github.com/pusher/pusher-websocket-swift#configuration)
