### ISSUE TITLE
WebSocket Compression

### ISSUE THREAD

**Issue by nicorichard** [pusher/pusher-websocket-swift#419]
Which versions of this library support the recently announced change to [enable websocket compression](https://pusher.com/blog/websocket-compression-pusher/) ?

Will my app continue to function if I am using this library? If I am using an old version of this library?

What protocols does this library support?

**Comment by knguyen-blaze** [comment]
Hello, I have the same question. Is v8.0.0 still supported?

**Comment by benw-pusher** [comment]
this library supports the correct protocols. We have now completed the deprecation activity.
