### ISSUE TITLE
Events are being sent on Main thread

### ISSUE THREAD

**Issue by parvez-keeptruckin** [pusher/pusher-websocket-swift#425]
### Steps to reproduce

- Used CocoaPods based version `PusherSwift (10.1.5)`
- Subscribe to a channel and event in Pusher. Start getting the event.

### Expected behavior

Events should be received on background thread. In case when frequency of event receipt is very high then receiving it on main thread seems not a good solution as it maybe that these events require some processing in background and one can switch to main thread if needed.

### Actual behavior

Events are being received on main thread.

![PusherEvent](https://github.com/pusher/pusher-websocket-swift/assets/87128187/87ef1939-8221-4df4-a2b1-d836cf276d37)

**Comment by benw-pusher** [comment]
I've passed this feedback on to the team however at this time we can't commit to a release for this change. You should implement the Channels integration on a background thread if this is required your app.
