### ISSUE TITLE
Can't Handle Auth Error

### ISSUE THREAD

**Issue by psycotica0** [pusher/pusher-websocket-swift#44]
Hey, just checking in case I'm missing something.

I have setup Auth, and it's working fine, but if I'm remembering a token which expires sometime in the future, I want to do logic when the auth request fails.

I've looked through the code and it looks like we're just logging the error and then doing nothing.

Is there a way I'm not seeing to get the error, or is this not currently implemented?

**Comment by hamchapman** [comment]
Hi @psycotica0 - currently it's not implemented. At the time I wasn't really sure of what the best mechanism would be to float the error up and to be honest I'm still not entirely sure of the best way of doing this.

If you've got any suggestions then please let me know, or you can always make a pull request 👍

**Comment by psycotica0** [comment]
I've made a pull request at #47.

I don't know how you feel about the approach, but it's what I'm using now.
Let me know what you think?

**Comment by hamchapman** [comment]
Merged in the code - just need to add a test for it so adding the 1.0.0 release milestone

**Comment by psycotica0** [comment]
Tests might be a good idea. I just made #49 about a bug I found while using the code I wrote in the last one. Specifically, the error was being dispatched on a background thread rather than the main one.

**Comment by hamchapman** [comment]
Closing as it's been merged (albeit with a small bug :) ). Fully working in v1.0.0 👍
