### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by wess** [pusher/pusher-websocket-swift#45]
Add logging for things like printing everything we get back from ```websocketDidReceiveMessage```?

Thank you

**Comment by hamchapman** [comment]
@wess I'll add this in for the 1.0.0 release (upcoming). If you fancy giving it a go though, then let me know and I'll hold off on doing it myself 👍

**Comment by hamchapman** [comment]
Added in 516493d366

**Comment by hamchapman** [comment]
1.0.0 has just been pushed
