### ISSUE TITLE
Connection STATES

### ISSUE THREAD

**Issue by marklochrie50265** [pusher/pusher-websocket-swift#46]
IM not sure if something is wrong with the api of Pusher's server. From looking at the debug console sometimes I see "connection" events and other i see this plus "occupied" but only when is the channel occupied i am able to receive data within the application is anyone else having this issue?

**Comment by hamchapman** [comment]
Hi Mark - that sounds expected to me. You'll only receive data if a client is subscribed and thus the channel occupied. Am I misunderstanding the problem you're facing?

**Comment by marklochrie50265** [comment]
That is right but sometimes ive noticed this behaviour not happening, i.e. the occupied state - I will update once im back in work

**Comment by hamchapman** [comment]
Hey @marklochrie50265, any updates or can I close this?
