### ISSUE TITLE
Use of undeclared type 'ConnectionStateChangeDelegate'

### ISSUE THREAD

**Issue by ranjitDhiman1990** [pusher/pusher-websocket-swift#48]
I am trying to integrate the PusherSwift in my example project. But I'm getting the following issues when building the app.

I am using the Xcode version - 7.2.1

1. Use of undeclared type 'ConnectionStateChangeDelegate'
2. Use of undeclared type 'ConnectionState'
<img width="896" alt="screen shot 2016-06-01 at 12 25 22 am" src="https://cloud.githubusercontent.com/assets/15705575/15686968/11505090-2790-11e6-9198-4dd21d580b44.png">

**Comment by hamchapman** [comment]
Hi there, which version of the library are you using?

**Comment by ranjitDhiman1990** [comment]
I'm using Pusher library version 0.3.0 and Xcode version 7.2.1

**Comment by hamchapman** [comment]
I can't seem to recreate this. Sorry to ask again, but are you _sure_ you're using 0.3.0? :)

**Comment by ranjitDhiman1990** [comment]
Sorry it was  PusherSwift (0.2.4)  and Xcode version 7.2.1
Here is my podfile.lock
PODS:
  - CryptoSwift (0.2.3)
  - PusherSwift (0.2.4):
    - CryptoSwift (~> 0.2.3)
    - ReachabilitySwift (~> 2.3.3)
    - Starscream (~> 1.1.2)
  - ReachabilitySwift (2.3.3)
  - Starscream (1.1.3)

DEPENDENCIES:
  - PusherSwift

SPEC CHECKSUMS:
  CryptoSwift: b2bf37b8e7cc6d682ef3365cb966bc5ae5174aa5
  PusherSwift: b84c870b3ad6021278f44b8893ed6ecce6a39584
  ReachabilitySwift: e0f6b6f280effb47731acfaaa2d5ffe223703793
  Starscream: d662732354b40dd19ed1ece3e3c44c80b536b83c

PODFILE CHECKSUM: 5dab043f061ebcc49d27c451432407f56734553f

COCOAPODS: 1.0.0

**Comment by hamchapman** [comment]
Thanks - looks like you've figured it out but just for anyone else who gets here, upgrade to v0.3.0+ and this error will go away 👍
