### ISSUE TITLE
connectionState is not updated when delegate's method connectionChange is called

### ISSUE THREAD

**Issue by thanhn08** [pusher/pusher-websocket-swift#50]
Hi,

I have experienced a case when user presses power button to turn phone's screen off or app is in background for a long enough time, and then they turn it on again and the app resumes, the socket connection is disconnected. I have implemented the stateChangeDelegate to manually connect but it doesn't work, because in your `connect()` method of PusherSwift.swift, it checks for connection state and return if it's connected. The problem is, at that moment the state was still connected (not updated to disconnected) because of this method 
```
private func updateConnectionState(newState: ConnectionState) {
    self.stateChangeDelegate?.connectionChange(self.connectionState, new: newState)
    self.connectionState = newState
}
```
It should update self.connectionState before calling the connectionChange on delegate. 

Also, I also suggest the method name should be `connectionChanged` not `connectionChange`. Normally we would more likely to handle the connection after it's changed from one state to another state, not before it will change (like my case to manually re-establish the connection). 

The autoReconnect doesn't work because the reachability event is not fired as the internet connection was fine, only the socket was disconnected (i think because of server closes connection)

Please check.

**Comment by hamchapman** [comment]
Both valid points - I'll change this for the 1.0.0 release which is here: #34

**Comment by thanhn08** [comment]
thank you.
