### ISSUE TITLE
How to monitor connection states?

### ISSUE THREAD

**Issue by utkbansal** [pusher/pusher-websocket-swift#53]
I need to delay the sending of the messages till when the connection comes back up. How do I do this? The messages should be preserved even if the app is force closed and should be sent the next time it runs.  

Can `func connectionChange(old: ConnectionState, new: ConnectionState` help in this?

**Comment by hamchapman** [comment]
You'd need to persist the messages yourself in some sort of data store, core data for example.

Then yes, you can use the `ConnectionStateDelegate` to update a variable that keeps track of whether or not the client is connected.

Obviously this works in terms of the client sending the messages (client events).

If you need to delay them based on sending them from a server then you again would need to use the `ConnectionStateDelegate` and implement some level of state storage on you server to determine whether or not a client is connected.
