### ISSUE TITLE
Clarification about auto reconnect feature

### ISSUE THREAD

**Issue by dral3x** [pusher/pusher-websocket-swift#64]
In the code here
https://github.com/pusher/pusher-websocket-swift/blob/master/Source/PusherWebsocketDelegate.swift#L43

you handle the disconnection of the socket, and try to reconnect automatically if the flag `autoReconnect` is set to true but you ignore if the socket has been closed for error or intentionally.

Is it intended or a bug? To me it's a bug but maybe I misunderstood the library behavior.
Thanks

**Comment by dral3x** [comment]
Debugging the situation I notice more strange things. Let me recap my use case:

I want to connect the Pusher client when user is actively interested in receiving realtime messages (I explicitly do the `connect` on the client).
When user leaves the app, I explicitly do the `disconnect`.

I expected that the connection goes from `Connected` -> `Disconnecting` -> `Disconnected` and stay there, but it's not the case.
A second later the connection moved from `Disconnected` to `Connected` again and the realtime message are coming in.

The error `Websocket is disconnected: connection closed by server` is printed in the console.
Here it is the full log after I explicitly request the disconnection of Pusher client.

```
2016-06-29 09:19:34.837 [DEBUG] [RealtimeClient disconnect()|88] Disconnect
2016-06-29 09:19:34.837 [DEBUG] [RealtimeClient connectionChange(_:new:)|190] State changed : Connected -> Disconnecting
Websocket is disconnected: connection closed by server
2016-06-29 09:20:12.925 [DEBUG] [RealtimeClient connectionChange(_:new:)|190] State changed : Disconnecting -> Disconnected
2016-06-29 09:20:14.796 [DEBUG] [RealtimeClient connectionChange(_:new:)|190] State changed : Disconnected -> Connected
```

Because an actual error is received, PusherWebsocketDelegate.swift#L33 should correctly trigger the reconnection (because there is an actual error to recover from).
But we should not received an error because we intentionally disconnect the socket.

Ideas on how to fix this?

**Comment by hamchapman** [comment]
Again, some changes have been made to autoReconnect behaviour on master, see #55 for more info

**Comment by dral3x** [comment]
I see that but the problem exist in that code as well. I'm using the latest version of the library.

I'm currently working on a fix. I will make a pull request soon so you can decide what to do about :)

**Comment by dral3x** [comment]
Here I am with #65

**Comment by hamchapman** [comment]
Merged. Will be in release along with the rest of #60
