### ISSUE TITLE
Replace abominable implementation of deviceTokenToString

### ISSUE THREAD

**Issue by jameshfisher** [pusher/pusher-websocket-swift#71]
https://github.com/pusher/pusher-websocket-swift/blob/push-notifications/Source/NativePusher.swift#L70-L77

see e.g. http://stackoverflow.com/a/24979958/229792

**Comment by hamchapman** [comment]
This is fixed in the Swift 3 branch. Will close this when that is master

**Comment by hamchapman** [comment]
Version 3.0.0 is now released 🎉  (with this fix included)
