### ISSUE TITLE
Migrate to Swift 2.3 and Swift 3

### ISSUE THREAD

**Issue by suchtomwow** [pusher/pusher-websocket-swift#73]
In order to migrate and test our app to Swift 2.3/3.0 prior to the release of Xcode 8 and iOS 10, all of our dependencies need to be migrated first.

This can be solved by pointing our podfile to those respective Swift 2.3/3.0 branches, but this repo does not appear to have either of those branches.

[This blog post](http://www.jessesquires.com/migrating-to-swift-3/) contains helpful tips for migrating open source libraries.

**Comment by hamchapman** [comment]
Yep - on my list of things to do. Will take a look at this very soon.

**Comment by hamchapman** [comment]
Branches created for 2.3 here:

(based off master): https://github.com/pusher/pusher-websocket-swift/tree/swift-2.3
(based off push-notifications): https://github.com/pusher/pusher-websocket-swift/tree/push-notifications-swift-2.3

**Comment by teddybee** [comment]
Good morning Hamchapman,

Are you planning to create Swift3 branch as well? 
The main changes in XCode8 beta6 are:
AnyObject replaced by Any and class names loosed the NS prefix

**Comment by hamchapman** [comment]
I'm hoping to get a swift 3 branch working on Monday. Sorry for the delay!

**Comment by hamchapman** [comment]
Both of these are created and working.

Swift 3 branch will become master today, along with a new release being made

**Comment by ejeklint** [comment]
Will the push-notification branch be swift 3-ified as well and merged into master?

**Comment by hamchapman** [comment]
Yep, that's already part of this branch

**Comment by hamchapman** [comment]
Version 3.0.0 is now released 🎉

**Comment by sherm4n90** [comment]
@hamchapman Im using the swift-2.3 branch and getting compiling errors in xcode 8. any solution? Tried with pod version 2.0.1 and got the same.

**Comment by hamchapman** [comment]
You'll need to use the `swift-2.3` branch, not the 2.0.1 release.

What compiler errors are you getting?

I just checked out the branch locally and built successfully without any errors using Xcode 8.

**Comment by sherm4n90** [comment]
@hamchapman Using version 2.0.1 and it works now. is that ok?

**Comment by hamchapman** [comment]
2.0.1 was based on Swift 2.2 but may well work for Swift 2.3 (there weren't really any changes to be made from memory). If it works then it's all good 👍

**Comment by sherm4n90** [comment]
@hamchapman It seems that all isn't good :(. For some reason the build errors show up again after a pod install. Using the 2.3 branch and working ok now. Thanks

**Comment by IzaacBarratt** [comment]
Is there no pod version for swift 2.3?

**Comment by sherm4n90** [comment]
Im using this branch: `pod 'PusherSwift', :git => 'https://github.com/pusher/pusher-websocket-swift.git', :branch => 'swift-2.3'` @IzaacBarratt
