### ISSUE TITLE
error: Value of type Pusher has no member 'nativePusher'

### ISSUE THREAD

**Issue by r-a-o** [pusher/pusher-websocket-swift#74]
Getting this error,

`Value of type Pusher has no member 'nativePusher'`

I am trying to setup pusher for receiving Push Notifications, 
Docs: https://pusher.com/docs/push_notifications/ios/client#register-with-pusher

> func application(application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken : NSData) {
>     pusher.nativePusher().register(deviceToken)
>     // ...
> }

**Comment by hamchapman** [comment]
I think it will be because you aren't using the correct version of PusherSwift.

Currently the version that supports native push is 2.1.0rc2.

You can use the following to install for Cocoapods or Carthage:

```ruby
pod 'PusherSwift', git: 'git@github.com:pusher/PusherSwift.git', branch: 'push-notifications'
```

```ogdl
github "pusher/pusher-websocket-swift" "2.1.0rc2"
```

If you need to install without Cocoapods of Carthage then let me know and I can run you through it.

**Comment by r-a-o** [comment]
Tried the Cocoapods install, getting this error,

> Pre-downloading: `PusherSwift` from `git@github.com:pusher/PusherSwift.git`, branch `push-notifications`
> 
> [!] Error installing PusherSwift
> [!] /usr/bin/git clone git@github.com:pusher/PusherSwift.git /var/folders/n2/../T/..-3102-1pz5mxz --template= --single-branch --depth 1 --branch push-notifications
> 
> Cloning into '/var/folders/n2/.../T/..-3102-1pz5mxz'...
> Permission denied (publickey).
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.

**Comment by r-a-o** [comment]
I couldn't get the branch the way you suggested, instead I had to do this to get the branch.
(probably because no public key check is done when using https)

`pod 'PusherSwift', git: 'https://github.com/pusher/pusher-websocket-swift.git', branch: 'push-notifications'`

**Comment by hamchapman** [comment]
Ah you're right - sorry about that. I left it in with SSH access assumed, which obviously isn't the case. 

I'll fix that up in the readme instructions - thanks!
