### ISSUE TITLE
Branch: push-notifications; Getting 'Bad HTTP Response'

### ISSUE THREAD

**Issue by r-a-o** [pusher/pusher-websocket-swift#76]
I am trying out the new push-notifications feature, I have done the integration, but on launching the app, I see the following message in my console,

> Bad HTTP response: Optional(<NSHTTPURLResponse: 0x14799550> { URL: https://nativepushclient-cluster1.pusher.com/client_api/v1/clients } { status code: 404, headers {
>     Connection = "keep-alive";
>     "Content-Length" = 77;
>     "Content-Type" = "application/json";
>     Date = "Wed, 10 Aug 2016 13:36:23 GMT";
>     Server = Cowboy;
>     Via = "1.1 vegur";
> } })

Has the URL endpoint changed?

**Comment by hamchapman** [comment]
Sorry for the delay in getting back to you: a 404 in that context means that the Pusher app id you're trying to use with the push notifications feature does not exist in the context of the push notifications service. 

Please could you raise a support ticket (if you've not already) and provide more specific app details?

Thanks!

**Comment by r-a-o** [comment]
I had not added the push notification certificate for the Pusher app.
Thanks.

**Comment by r-a-o** [comment]
After adding the push notification certificate for the pusher app,
I am now getting 401 response,

> Bad HTTP response: Optional(<NSHTTPURLResponse: 0x15ee89a0> { URL: https://nativepushclient-cluster1.pusher.com/client_api/v1/clients } { status code: 401, headers {
>     Connection = "keep-alive";
>     "Content-Length" = 388;
>     "Content-Type" = "text/plain; charset=utf-8";
>     Date = "Fri, 19 Aug 2016 15:58:33 GMT";
>     Server = Cowboy;
>     Via = "1.1 vegur";
> } })

I am using the production key, is that a problem? I mean how do I switch between dev key and prod key on the app?

**Comment by suprb** [comment]
Same here — any ideas?

Bad HTTP response: Optional( { URL: https://nativepushclient-cluster1.pusher.com/client_api/v1/clients } { status code: 401, headers {
    Connection = "keep-alive";
    "Content-Length" = 388;
    "Content-Type" = "text/plain; charset=utf-8";
    Date = "Fri, 26 Aug 2016 03:06:59 GMT";
    Server = Cowboy;
    Via = "1.1 vegur";
} })

**Comment by vivangkumar** [comment]
Hi there,

Could you double check that you've added the correct push notification certificate? A 404 is returned in this context when we were unable to verify that the device you're trying to register is authorised to receive push notifications.

**Comment by suprb** [comment]
@vivangkumar — it's a **401** error for both me and @r-a-o

**Comment by vivangkumar** [comment]
Sorry, yes. I did mean a 401 error.

**Comment by r-a-o** [comment]
@vivangkumar I am using the production keys and running the app on my device connected to Xcode via USB. 
Is this why Pusher throwing a 401?
If yes, how does Pusher know that the app is not from App Store & is run locally?

**Comment by vivangkumar** [comment]
Could you please raise a support ticket at support.pusher.com?

In the email, its best if you include your pusher app id and other details so we can help you out as best as possible.

**Comment by r-a-o** [comment]
Submitted a ticket, will update this thread when I have something.

**Comment by suprb** [comment]
Same here — I'll provide my process here as well.

**Comment by suprb** [comment]
In my case, I accidentally put Production instead of Development in the Pusher Dashboard's Push Notification tab. Works now.
