### ISSUE TITLE
tryFlushOutbox is not thread-safe

### ISSUE THREAD

**Issue by jameshfisher** [pusher/pusher-websocket-swift#83]
This is unconfirmed, but I expect pusher-websocket-swift to have the same bug as that in libPusher: https://github.com/pusher/libPusher/issues/230

https://github.com/pusher/pusher-websocket-swift/blob/push-notifications/Source/NativePusher.swift#L168

**Comment by hamchapman** [comment]
I'm looking into this today, with a view to a 3.0.1 release if I get it all working

**Comment by hamchapman** [comment]
PR that should fix this: https://github.com/pusher/pusher-websocket-swift/pull/90

**Comment by hamchapman** [comment]
#90 is merged
