### ISSUE TITLE
Issue with CryptoSwiftHMACModule.swift 

### ISSUE THREAD

**Issue by krzyzanowskim** [pusher/pusher-websocket-swift#89]
Regarding: [CryptoSwiftHMACModule.swift](https://github.com/pusher/pusher-websocket-swift/blob/swift-3/Source/CryptoSwiftHMACModule.swift)

Hi, I'm the author of [CryptoSwift](https://github.com/krzyzanowskim/CryptoSwift) and find out that you copied bunch of CryptoSwift code to single swift file. That's fine. The issue is that it interfere with CryptoSwift itself now. This is because you left public functions from extenstions that you probably don't need as public. In particular there is [toHexString()](https://github.com/pusher/pusher-websocket-swift/blob/swift-3/Source/CryptoSwiftHMACModule.swift#L135) and others that may cause problems. Please make it internal for your module only.

Ref: https://github.com/krzyzanowskim/CryptoSwift/issues/328

Another thing is licence compliance. As you [may notice](https://github.com/pusher/pusher-websocket-swift/blob/swift-3/Source/CryptoSwiftHMACModule.swift#L8)
> If you use this software in a product, an acknowledgment in the product documentation is required.

If you're interested in non-attribution licence, please contact me.

Thanks!

**Comment by hamchapman** [comment]
Thanks for the input!

I've added a note in the README: 1b14440f

I've also made all of the access levels `internal` as you suggested: 5d7595507c

**Comment by teddybee** [comment]
Thank you guys, the errors were gone.
