### ISSUE TITLE
Which swift version is currently supported?

### ISSUE THREAD

**Issue by MladenBekavac** [pusher/pusher-websocket-swift#91]
I have tried to setup the project on Swift 2.2. but I have recieved about 500 errors. 

I couldn't find which is the current up to date version of Swift with which pusher works?

**Comment by hamchapman** [comment]
Swift 3 is the version of Swift used on master and since version 3.0.0 of the library. 

If you want to use an older version of Swift then you will need to use one of the older versions of the library, i.e. < v3.0.0

Thanks 👍

**Comment by MladenBekavac** [comment]
Thank you for your quick response. It seems that I can't get the older versions via CocoaPods. The following statements didn't work.
pod 'PusherSwift', '2.1.0rc2’
pod 'PusherSwift', '2.1.’
pod 'PusherSwift', '< 3.0.0’

Q1. Is there any way to add the older framework version via CocoaPods?

NOTE: I need the older version due other frameworks which don't work with Swift 3.0.

**Comment by hamchapman** [comment]
If you don't need the push notification related code then you should use version 2.1.0.

Otherwise you should be able to use it with this in your Podfile:

```
pod 'PusherSwift', git: 'https://github.com/pusher/pusher-websocket-swift.git', branch: 'push-notifications'
```

**Comment by MladenBekavac** [comment]
Thank you. I works like a charm =). (Xcode 7.3., Swift 2.2).

**Comment by jjulian** [comment]
Ideally, a project will release specific versions for compatibility with specific versions of Swift. Right now, projects can be on Swift 2.2 (Xcode 7), Swift 2.3 (Xcode 8), or Swift 3.0 (Xcode 8).

I'd rather point my Podfile to a version, than a branch.

For instance, you could state that 2.0.x is Swift 2.2 compatible, 2.1.x is Swift 2.3, and 3.0.x is Swift 3.0. See the "Backwards Compatibilty" section of XCGLogger [here](https://github.com/DaveWoodCom/XCGLogger) for a great example.

Just a thought to clean things up. Thanks. 😄

**Comment by pushpankq** [comment]
How to run PusherSwift pod in Swift 3.0 ? PusherSwift is written in Swift 2.3.

**Comment by hamchapman** [comment]
PusherSwift has been written using Swift 3+ syntax since the 3.0.0 release of the PusherSwift library: https://github.com/pusher/pusher-websocket-swift/blob/master/CHANGELOG.md#300

**Comment by pushpankq** [comment]
When I install the pod and open the project xcode shows a pop for language
(I have attach a screenshot for that). What I should for use it.

**Comment by hamchapman** [comment]
I'm not sure what you mean. Do you have the screenshot?

Once you've done `pod install` you'll need to open the generated `.xcworkspace` file, not the `.xcodeproj` file.

**Comment by pushpankq** [comment]
I am opening .xcworkspace file, not the .xcodeproj file but it shows the
error "

*The target “PusherSwift” contains source code developed with an earlier
version of Swift.*

*Choose “Convert” to update the source code in this project to the latest
SDKs. You will be given the choice to use Swift 2.3 syntax or update to
Swift 3.*
*This action can be performed later using “Convert to Current Swift Syntax”
in the Edit menu.*" And Please find an attachments.

Thanks

**Comment by hamchapman** [comment]
The attachment hasn't worked I'm afraid.

And which version of Xcode are you using?

**Comment by pushpankq** [comment]
I'm using XCode 8.2.1. Please find the attachment.

**Comment by hamchapman** [comment]
Unfortunately there's still no attachment. Perhaps you can't add media when replying via email and you'll need to use the GitHub UI instead?
