### ISSUE TITLE
Provide correct example of initial presence members

### ISSUE THREAD

**Issue by jameshfisher** [pusher/pusher-websocket-swift#92]
The README has examples like this:

```
let chan = pusher.subscribe("presence-channel")
print(chan.members)
```

This is misleading: the `chan.members` at that point is empty, because the subscription has not yet succeeded. I assumed that the call must be blocking.

It wasn't blocking. I then assumed that the optional `onMemberAdded`/`onMemberRemoved` callbacks would be called when the subscription succeeded, so I implemented that. But this was not the case either.

Eventually I found I had to:

* implement `PusherConnectionDelegate`
* set `pusher.connection.delegate`
* get the `members` property only when the channel with the right name comes through in the `subscriptionDidSucceed` callback, like so:

```
    func subscriptionDidSucceed(channelName: String) {
        if channelName == "presence-foo" {
            print(self.presenceChannel!.members, "\n");
        }
    }
```

I think there are similar misleading examples like `chan.me()` which should also be fixed.

**Comment by hamchapman** [comment]
I think just below that example is where I explained it: https://github.com/pusher/pusher-websocket-swift#presence-channels, with the comment about how there's the `subscribeToPresenceChannel` function available, if you want to have direct access to the `members`, `me` etc functions without having to cast.

Although your comment seems to be more about how they don't return anything useful until a successful subscription occurs, which is also a good point.

Two things:

1) I thought it would be confusing to have the `onMemberAdded` event fire for the client itself being added as a member, so made it not do that. I could, however, make it fire for that case. What I think I would prefer to do though is...

2) Adding a function that you can chain to subscriptions on presence channels which would look something like:

```swift
let presenceChan = pusher.subscribeToPresenceChannel("presence-chan") { chan in
  // then in here you have can add some code you want to be run
  // only when connection has succeeded
}
```

Or maybe a docs change is enough?

@jameshfisher WDYT?

**Comment by jameshfisher** [comment]
I think a docs change is enough:

* I didn't even see the `subscribeToPresenceChannel` bit because I didn't read that far!
* I'd remove any mention of `pusher.subscribe("presence-my-channel")` if we want to replace it with `subscribeToPresenceChannel`
* Remove any examples which imply that members etc are synchronously populated
* Expand the single example of `subscribeToPresenceChannel` to show how to:

  * get the current set of members
  * get changes to the set of members

**Comment by hamchapman** [comment]
Updated the docs to make working with presence channels a lot clearer. See 5cd469c8 for reference.

**Comment by jameshfisher** [comment]
Much better! Thanks!
