### ISSUE TITLE
Swift example should call completion handler

### ISSUE THREAD

**Issue by jameshfisher** [pusher/pusher-websocket-swift#95]
Swift example for receiving notifications in README:

```
func application(_ application: UIApplication, didReceiveRemoteNotification userInfo: [AnyHashable : Any], fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void) {
    print(userInfo)
}
```

I think this violates [the documentation for this callback](https://developer.apple.com/reference/uikit/uiapplicationdelegate/1623013-application) which says

> As soon as you finish processing the notification, you must call the block in the handler parameter or your app will be terminated.

I would suggest immediately calling the completion handler with `.newData`.

**Comment by hamchapman** [comment]
Fixed in 254e6b7
